### ISSUE TITLE
Fail to nested update

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1233]
**Describe the bug**
Fail to nested update

**Type definitions**
```
type Human {
  id:ID @id
  name: String @unique
  blog: [Blog!]! @relationship(type:"HAS_BLOG", direction: OUT)
}

type Blog {
  id:ID @id
  name: String @unique
  comment: [Comment!]! @relationship(type:"WITH_COMMENT", direction: OUT)
}

type Comment {
  id:ID @id
  name: String @unique
  author: Author @relationship(type:"AUTHOR_IS", direction: OUT)
}

type Author{
  id:ID @id
  name: String @unique
}
```

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
```
mutation createHm{
	createHumans(input:[
		{
			name:"name of human"
			blog:{
				create:{
					node:{
						name:"name of blog"
						comment:{
							create:{
								node:{
									name:"name of comment"
									author:{
										create:{
											node:{
												name:"name of author"
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	]){
		humans{
			id
			name
			blog{
				id
				name
				comment{
					id
					name
					author{
						id
						name
					}
				}
			}
		}
	}
}
```

4. Then run the following Query...
```
query queryHm{
	humans{
			id
			name
			blog{
				id
				name
				comment{
					id
					name
					author{
						id
						name
					}
				}
			}
		}
}
```
----------

```
mutation updateHm {
	updateHumans(
		where: { name:"name of human" }
		update: {
			name: null
			blog: 
				{
					where: { node: { name:"name of blog" } }
					update: {
						node: {
							name: "updated name of blog"
							comment: 
								{
									where: {
										node: { name:"name of comment" }
									}
									update: {
										node: {
											name: "updated name of comment"
											author: {
												where: {
													node: { name:"name of author" }
												}
												update: {
													node: { name: "updated name of author" }
												}
											}
										}
									}
								}
							
						}
					}
				}
		}
	) {
		humans {
			id
		}
	}
}
```

6. See error
```
{
	"errors": [
		{
			"message": "Failed to invoke procedure `apoc.do.when`: Caused by: org.neo4j.exceptions.SyntaxException: Invalid input 'E': expected 't/T' (line 15, column 2 (offset: 1115))\r\n\"SET this_blog0_comment0_author0.name = $this_update_blog0_comment0_author0_name\"\r\n  ^",
			"locations": [
				{
					"line": 67,
					"column": 2
				}
			],
			"path": [
				"updateHumans"
			],
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"exception": {
					"code": "Neo.ClientError.Procedure.ProcedureCallFailed",
					"name": "Neo4jError",
					"stacktrace": [
						"Neo4jError: Failed to invoke procedure `apoc.do.when`: Caused by: org.neo4j.exceptions.SyntaxException: Invalid input 'E': expected 't/T' (line 15, column 2 (offset: 1115))\r",
						"\"SET this_blog0_comment0_author0.name = $this_update_blog0_comment0_author0_name\"\r",
						"  ^",
						"",
						"    at captureStacktrace (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\result.js:239:17)",
						"    at new Result (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\result.js:59:23)",
						"    at newCompletedResult (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\transaction.js:433:12)",
						"    at Object.run (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\transaction.js:287:20)",
						"    at Transaction.run (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\transaction.js:137:34)",
						"    at transactionWork (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\@neo4j\\graphql\\dist\\utils\\execute.js:58:44)",
						"    at TransactionExecutor._safeExecuteTransactionWork (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:92:26)",
						"    at TransactionExecutor._executeTransactionInsidePromise (C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:83:34)",
						"    at C:\\Users\\yfo\\VisualstudioProjects\\neo4j-graphql-example\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:40:19",
						"    at new Promise (<anonymous>)"
					]
				}
			}
		}
	],
	"data": null
}
```
**Expected behavior**
no error will throw

**Screenshots**

**System (please complete the following information):**

* Version: [e.g. @neo4j/graphql@3.0.3]

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AnsonHwang86. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @AnsonHwang86! Thanks for reaching out!
The provided steps do not resolve in an error for me when using `@neo4j/graphql@3.0.3`, the `updateHm` mutation returns a valid result.
Would you be able to double check the provided queries in this bug report?

**Comment by AnsonHwang86** [comment]
Hello @tbwiss , sorry. my version is `@neo4j/graphql@3.0.2`.
Has  `@neo4j/graphql@3.0.3` fixed this bug?

**Comment by darrellwarde** [comment]
> Hello @tbwiss , sorry. my version is `@neo4j/graphql@3.0.2`. Has `@neo4j/graphql@3.0.3` fixed this bug?

Quite possibly - can you please upgrade and give it a go for us?

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AnsonHwang86! :pray: We will now prioritise the bug and address it appropriately.

**Comment by tbwiss** [comment]
Hi @AnsonHwang86! Would you be able to upgrade to 3.1.0 and give it a try? [3.1.0](https://www.npmjs.com/package/@neo4j/graphql) has just been released

**Comment by AnsonHwang86** [comment]
@tbwiss . Just tried it at 3.1.0. It work fine. Hope to find the reason why this happen. Thanks.
