### ISSUE TITLE
Broken docs?

### ISSUE THREAD

**Issue by gaving** [neo4j/graphql#1235]
**Describe the bug**

Hi! Just trying the documentation at https://neo4j.com/developer/graphql/#_using_the_neo4j_graphql_library_with_neo4j_auradb

Seems to give:-

```
❯ node index.js
/Users/gavin/Junk/test/node_modules/apollo-server-core/dist/ApolloServer.js:333
            throw Error('Apollo Server requires either an existing schema, modules or typeDefs');
            ^

Error: Apollo Server requires either an existing schema, modules or typeDefs
    at ApolloServer.constructSchema (/Users/gavin/Junk/test/node_modules/apollo-server-core/dist/ApolloServer.js:333:19)
    at new ApolloServerBase (/Users/gavin/Junk/test/node_modules/apollo-server-core/dist/ApolloServer.js:140:75)
    at new ApolloServer (/Users/gavin/Junk/test/node_modules/apollo-server-express/dist/ApolloServer.js:13:1)
    at new ApolloServer (/Users/gavin/Junk/test/node_modules/apollo-server/dist/index.js:31:9)
    at Object.<anonymous> (/Users/gavin/Junk/test/index.js:27:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Node.js v17.8.0
```

* OS: Both Mac/Windows
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: 17.8.0 and 14.17.4

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@neo4j/graphql": "^3.0.4",
    "apollo-server": "^3.6.7",
    "dotenv": "^16.0.0",
    "graphql": "^16.3.0",
    "neo4j-driver": "^4.4.5"
  }
}
```

Is there a possible API change at the apollo-server package side? 

Thanks!

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @gaving. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @gaving!
Thanks for reaching out! And yes indeed, the documentation under [https://neo4j.com/developer/graphql/#_using_the_neo4j_graphql_library_with_neo4j_auradb](https://neo4j.com/developer/graphql/#_using_the_neo4j_graphql_library_with_neo4j_auradb) hasn't been updated to reflect the changes made  `@neo4j/graphql` 3.0.0. We will fix that. Thanks for pointing it out!
Glad that you found the solution in the [Neo4j GraphQL library documentation](https://neo4j.com/docs/graphql-manual/current/getting-started/#_create_an_instance_of_apolloserver). Since `@neo4j/graphql` 3.0.0 the schema is generated asynchronous, hence the Promise or `await`.

**Comment by tbwiss** [comment]
PR opened in the `neo4j-documentation / developer-guides` repo: https://github.com/neo4j-documentation/developer-guides/pull/223

**Comment by gaving** [comment]
Thanks for sorting that @tbwiss!
