### ISSUE TITLE
Unexpected behaviour when @cypher properties don't use `this`

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#1476]
**Describe the bug**
Our database has lots of `AWSResource` records each with a `resourceType` property. I'm trying to write a top level query to list all the resource types. When defining tis property as a top level property on `Query` only the first item is returned (running the query in the neo4j console returns 20 different results). When adding a similar property to another type just to see if defining the cypher statement at the top level was the problem it throws an error

**Type definitions**
```graphql
   type System {
        code: String!
        awsResourceTypes: [String] @cypher(statement: "MATCH (awsResource:AWSResource) RETURN DISTINCT awsResource.resourceType")
   }

   type AWSResource {
       resourceType: String
   }

   type Query {
       awsResourceTypes: [String] @cypher(statement: "MATCH (awsResource:AWSResource) RETURN DISTINCT awsResource.resourceType")
   }
```

**To Reproduce**

1. Run a neo4j graphql server with the schema above. Create at least one System record and several AWSResource records with a variety of `resourceType` values. no need to create any relationships
2. Run this Query:
```
{
  systems(options: { limit: 1 }) {
    awsResourceTypes
  }
  awsResourceTypes
}
```

**Expected behavior**
Both `awsResourceTypes` properties contain a list of strings

**Actual behaviour**
```js
{
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"System.awsResourceTypes\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "systems",
        0,
        "awsResourceTypes"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Expected Iterable, but did not find one for field \"System.awsResourceTypes\".",
          "stacktrace": [
            "GraphQLError: Expected Iterable, but did not find one for field \"System.awsResourceTypes\".",
            "    at completeListValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:668:11)",
            "    at completeValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:607:12)",
            "    at executeField (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:489:19)",
            "    at executeFields (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:413:20)",
            "    at completeObjectValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:914:10)",
            "    at completeValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:635:12)",
            "    at completeValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:584:23)",
            "    at /Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:696:25",
            "    at Function.from (<anonymous>)",
            "    at completeListValue (/Users/rhys.evans/Projects/biz-ops-api-playground/node_modules/graphql/execution/execute.js:676:34)"
          ]
        }
      }
    }
  ],
  "data": {
    "systems": [
      {
        "awsResourceTypes": null
      }
    ],
    "awsResourceTypes": [
      "AWS::IAM::Policy"
    ]
  }
}
```

**System (please complete the following information):**

* OS: macOS
* Version: 3.2.3
* Node.js version: v14.18.3

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @wheresrhys. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by wheresrhys** [comment]
I wonder actually if this is more to do with returning a list of scalars from @cypher. I don't see anywhere explicitly in the docs that is supported. I'd be happy to submit a PR to add support

**Comment by tbwiss** [comment]
Hi @wheresrhys! Thanks for reaching out!
I was thinking around your comment with returning a list of scalars. Have you tried altering the `@cypher` statement to return a list?
For instance like this:
```
....
awsResourceTypes: [String] @cypher(statement: "MATCH (awsResource:AWSResource) WITH DISTINCT awsResource return COLLECT(awsResource.resourceType)")
....
```
See the cypher [collect() function](https://neo4j.com/docs/cypher-manual/4.4/functions/aggregating/#functions-collect).
Would that solve your issue?

**Comment by wheresrhys** [comment]
Thanks @tbwiss 

Yes, something close to that worked `MATCH (a:AWSResource) WITH DISTINCT a.resourceType as types return COLLECT(types)`

Is this reliance on getting collections rather than single properties of results in a standard result set worth documenting. Now you've pointed it out I can see that both are not equivalent, and only the former is actually covered by the tests, but it's not obvious the latter wouldn't work. 

In fact, I would even make this a feature request to support the latter as it enables writing far simpler cypher statements

Thanks again 😄
