### ISSUE TITLE
GraphQL reserved words clash with Entity names - apollo graphql server fails to start

### ISSUE THREAD

**Issue by TilakMaddy** [neo4j/graphql#1606]
GraphQL reserved words clash with Entity names - apollo graphql server fails to start

So rightfully I have coded my typeDefinitions as follows

```gql
const typeDefs = gql`
  type PipingConnection @exclude(operations: [CREATE, UPDATE, DELETE]) {
    conn_point_id: ID!,
    targetItem: PipingTargetItem! @relationship(type: "PipingConnection.TargetItem", direction: OUT)
  }
  type PipingTargetItem @exclude(operations: [CREATE, UPDATE, DELETE]) {
    lineId: ID!,
    sourceItem: PipingConnection! @relationship(type: "PipingConnection.TargetItem", direction: IN)
  }
`;
```

To Reproduce
In the full stack template created by @johnymontana  at https://github.com/johnymontana/fullstack-graphql-neo4j-auradb-nextjs-vercel-workshop , change the type definitions in the `nextjs/pages/api/graphql.js` to the above.

Now, when I visit `/api/graphql` I get this error

<img width="1279" alt="Screenshot 2022-06-20 at 6 12 41 PM" src="https://user-images.githubusercontent.com/11134428/174617625-c1f55388-1f01-44e4-88f1-380b5e258ea6.png">

The link shown to the relay website is [https://relay.dev/graphql/connections.htm#sec-Reserved-Types](https://relay.dev/graphql/connections.htm#sec-Reserved-Types) 

It says

>A GraphQL server which conforms to this spec must reserve certain types and type names to support the pagination model of connections. In particular, this spec creates guidelines for the following types:
>
>Any object whose name ends in **“Connection”.**
>
>An object named **PageInfo**.

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: [e.g. 14.16.0]

**Additional context**

Now, the problem is I cannot afford to rename the nodes in my Neo4J graph database because it is created to align with an industry-standard ontology.

So please suggest a workaround/solution for this.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @TilakMaddy. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @TilakMaddy! Thanks for reaching out!
One way to work around this is by using the `@node` directive, see [here](https://neo4j.com/docs/graphql-manual/current/type-definitions/database-mapping/#type-definitions-node) in the documentation. So something along the line of this:
```graphql
type PipingCon @exclude(operations: [CREATE, UPDATE, DELETE]) @node(label: "PipingConnection") {
    conn_point_id: ID!
    targetItem: PipingTargetItem! @relationship(type: "PipingConnection_TargetItem", direction: OUT)
}
type PipingTargetItem @exclude(operations: [CREATE, UPDATE, DELETE]) {
    lineId: ID!
    sourceItem: PipingCon! @relationship(type: "PipingConnection_TargetItem", direction: IN)
}
```
On another note: if at all possible, please do **not** use a dot in the relationship type name. Preferably make use of the underscore instead. See [naming conventions](https://neo4j.com/docs/cypher-manual/current/syntax/naming/).

**Comment by TilakMaddy** [comment]
Hey @tbwiss  thanks for the solution but I have one more requirement which is that the ontology expects a dot in the relationship. So please tell me what problems I should expect with that and what's the workaround ?

**Comment by TilakMaddy** [comment]
Here's the error with the  query

```gql
# Write your query or mutation here
{
  pipingTargetItems {
    lineId
    targetItem {
      conn_point_id
    }
  }
}
```

Error
```gql{
  "errors": [
    {
      "message": "Invalid input '[': expected\n  \"(\"\n  \"-\"\n  \"ALL\"\n  \"ANY\"\n  \"CASE\"\n  \"EXISTS\"\n  \"EXTRACT\"\n  \"FILTER\"\n  \"NONE\"\n  \"REDUCE\"\n  \"SINGLE\"\n  \"\\\"\"\n  \"\\'\"\n  \"allShortestPaths\"\n  \"count\"\n  \"null\"\n  \"shortestPath\"\n  \"{\"\n  <DECIMAL_DOUBLE>\n  <UNSIGNED_DECIMAL_INTEGER>\n  <UNSIGNED_HEX_INTEGER>\n  <UNSIGNED_OCTAL_INTEGER>\n  a parameter\n  an identifier (line 2, column 51 (offset: 80))\n\"RETURN this { .lineId, targetItem: head([ (this)<-[:PipingConnection.TargetItem]-(this_targetItem:`PipingConnection`)   | this_targetItem { .conn_point_id } ]) } as this\"\n                                                   ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "pipingTargetItems"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.SyntaxError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Invalid input '[': expected",
            "  \"(\"",
            "  \"-\"",
            "  \"ALL\"",
            "  \"ANY\"",
            "  \"CASE\"",
            "  \"EXISTS\"",
            "  \"EXTRACT\"",
            "  \"FILTER\"",
            "  \"NONE\"",
            "  \"REDUCE\"",
            "  \"SINGLE\"",
            "  \"\\\"\"",
            "  \"\\'\"",
            "  \"allShortestPaths\"",
            "  \"count\"",
            "  \"null\"",
            "  \"shortestPath\"",
            "  \"{\"",
            "  <DECIMAL_DOUBLE>",
            "  <UNSIGNED_DECIMAL_INTEGER>",
            "  <UNSIGNED_HEX_INTEGER>",
            "  <UNSIGNED_OCTAL_INTEGER>",
            "  a parameter",
            "  an identifier (line 2, column 51 (offset: 80))",
            "\"RETURN this { .lineId, targetItem: head([ (this)<-[:PipingConnection.TargetItem]-(this_targetItem:`PipingConnection`)   | this_targetItem { .conn_point_id } ]) } as this\"",
            "                                                   ^",
            "",
            "    at captureStacktrace (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/result.js:239:17)",
            "    at new Result (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/result.js:59:23)",
            "    at newCompletedResult (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/transaction.js:433:12)",
            "    at Object.run (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/transaction.js:287:20)",
            "    at Transaction.run (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/transaction.js:137:34)",
            "    at /Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/@neo4j/graphql/dist/utils/execute.js:66:104",
            "    at TransactionExecutor._safeExecuteTransactionWork (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)",
            "    at /Users/tilak/Documents/work/GitLab/fullstack-graphql-dexpi/nextjs/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}

```

**Comment by TilakMaddy** [comment]
It looks like the generated cypher is not using backticks around relationship that why `.` is interpreted as a sort of hexadecimal. How do we force use the backticks around the relationship ? Thank you

**Comment by TilakMaddy** [comment]
Hey @tbwiss  I think I just figured it out 
I did this

```gql
 type PipingCon @exclude(operations: [UPDATE, DELETE]) @node(label: "PipingConnection") {
    conn_point_id: ID!
    sourceItem: PipingTargetItem! @relationship(type: "\`PipingConnection.TargetItem\`", direction: OUT)
  }
  type PipingTargetItem @exclude(operations: [UPDATE, DELETE]) {
    lineId: ID!
    targetItem: PipingCon! @relationship(type: "\`PipingConnection.TargetItem\`", direction: IN)
  }
```

and it worked !
