### ISSUE TITLE
TypeError: types is not iterable

### ISSUE THREAD

**Issue by Dajust** [neo4j/graphql#1630]
**Describe the bug**
Migrating from v2.* to 3
When constructing the library instance, calling `neoSchema.getSchema()` throws `TypeError: types is not iterable` as show bellow.
```
/.../node_modules/@neo4j/graphql/node_modules/@graphql-tools/merge/index.cjs.js:785
    for (const type of types) {
                       ^

TypeError: types is not iterable
    at visitTypeSources (/.../node_modules/@neo4j/graphql/node_modules/@graphql-tools/merge/index.cjs.js:785:24)
    at mergeGraphQLTypes (/.../node_modules/@neo4j/graphql/node_modules/@graphql-tools/merge/index.cjs.js:811:5)
    at Object.mergeTypeDefs (/.../node_modules/@neo4j/graphql/node_modules/@graphql-tools/merge/index.cjs.js:766:22)
    at makeExecutableSchema (/.../node_modules/@neo4j/graphql/node_modules/@graphql-tools/schema/index.js:496:38)
    at /.../node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:137:74
    at new Promise (<anonymous>)
    at Neo4jGraphQL.generateSchema (/.../node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:127:16)
    at Neo4jGraphQL.getSchema (/.../node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:69:32)
```
Tracing the stack, I found that the culprit is the function `makeAugmentedSchema`: https://github.com/neo4j/graphql/blob/f660377cd0c657298564020262410efae3e399d3/packages/graphql/src/schema/make-augmented-schema.ts#L88

The function `makeAugmentedSchema` takes an iterable `typeDefs` and returns some object when it is called by `generateSchema`  here:
https://github.com/neo4j/graphql/blob/f660377cd0c657298564020262410efae3e399d3/packages/graphql/src/classes/Neo4jGraphQL.ts#L186
**Type definitions**
This is the same Type Definitions I've been using in v2

```
// message.gql

enum MessageType {
  MESSAGE
  ANNOUNCEMENT
}

enum MessageStatus {
  SENDING
  SENT
  DELIVERED
  READ
}

union Recipient = User | Room

type Message {
  id: ID! @id
  body: String!
  type: MessageType!
  status: MessageStatus
  to: Recipient! @relationship(type: "TO", direction: OUT)
  from: User! @relationship(type: "SENT", direction: IN)
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime @timestamp(operations: [UPDATE])
}
```

```
export const typeDefs = [
  rootSchema,
  message.schema,
  user.schema,
  ...
];
```

**Expected behavior**
Calling the function `makeAugmentedSchema` should return an iterable schema to the `generateSchema`.

**System (please complete the following information):**

* OS: macOs
* Version: @neo4j/graphql@3.4.0
* Node.js version: 16.6.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Dajust. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @Dajust! Thanks for reaching out!
When using v3.4.0 of the library with the above-given type defs I do not get any errors. Would you be able to share how you start the server and what you exactly pass to it? Also how you create the schema using the `Neo4jGraphQL` class would be of interest.
Thank you!

**Comment by Dajust** [comment]
Hey @tbwiss, thanks for responding.

Yes, I've tried with all versions of 3.x. Here's how I construct my `Neo4jGraphQL` instance.

```js
export const driver = neo4j.driver(
  NEO4J_DB,
  neo4j.auth.basic(NEO4J_USER, NEO4J_PASSWORD)
);

export const ogm = new OGM({ typeDefs, driver });

export const neoSchema = new Neo4jGraphQL({
  typeDefs,
  resolvers,
  driver,
  config: { enableDebug: true },
});

export async function createApolloServerConfig() {
  console.log('Creating schema...');

  // never exucte pass this point...
  const schema = await neoSchema.getSchema();

  const subscriptionServerOptions: ServerOptions = {
    schema,
    execute,
    subscribe,
    ...
  };

  const config: Config<ExpressContext> = {
    schema,
    debug: true,
    ...
  };

  return { subscriptionServerOptions, apolloServerConfig: config };
}
```
**Type Def**
```
const schema = gql`
  type User {
    id: ID! @id
    firstName: String!
    lastName: String!
  }
`;

export const typeDefs = [
  schema
];
```

**Comment by tbwiss** [comment]
Hi @Dajust!
Thanks for your update. I just executed your provided code, @neo4j/graphql v3.5.0 on a Mac with node v16, without it resulting in an error. Just for reference, here is the code I used: (for simplicity I put it all in one file)
```typescript
const schema = gql`
  type User {
    id: ID! @id
    firstName: String!
    lastName: String!
  }
`;

export const typeDefs = [schema];

export const driver = neo4j.driver(
  "url-xxxx",
  neo4j.auth.basic("neo4j", "xxxxxx")
);

export const neoSchema = new Neo4jGraphQL({
  typeDefs,
  //   resolvers,   // no custom resolvers
  driver,
  config: { enableDebug: true },
});

export async function createApolloServerConfig() {
  console.log("Creating schema...");

  // never exucte pass this point...
  const schema = await neoSchema.getSchema();
  console.log(schema.getDirectives());          // <- this gets executed

  return { schema };
}
createApolloServerConfig();
```

**Comment by tbwiss** [comment]
Hi @Dajust, since we were not able to reproduce this I'm going to close this issue. Feel free to re-open it when new findings or information appear.
