### ISSUE TITLE
Cannot query cypher fields on root connections when sort is not provided as an argument

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#1735]
If you query a root level connection where the node has a cypher field, you'll get an error.

```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'find')",
      "path": [
        "organizationsConnection"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Cannot read properties of undefined (reading 'find')",
          "path": [
            "organizationsConnection"
          ],
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'find')",
            "    at reducer (/Users/litewarp/Projects/tltf/node_modules/.pnpm/@neo4j+graphql@3.3.0_iwp6h2plez23ko5pkvojd3kjfq/node_modules/@neo4j/graphql/dist/translate/create-projection-and-params.js:233:45)",
            "    at Array.reduce (<anonymous>)",
            "    at createProjectionAndParams (/Users/litewarp/Projects/tltf/node_modules/.pnpm/@neo4j+graphql@3.3.0_iwp6h2plez23ko5pkvojd3kjfq/node_modules/@neo4j/graphql/dist/translate/create-projection-and-params.js:504:70)",
            "    at translateRead (/Users/litewarp/Projects/tltf/node_modules/.pnpm/@neo4j+graphql@3.3.0_iwp6h2plez23ko5pkvojd3kjfq/node_modules/@neo4j/graphql/dist/translate/translate-read.js:59:67)",
            "    at resolve (/Users/litewarp/Projects/tltf/node_modules/.pnpm/@neo4j+graphql@3.3.0_iwp6h2plez23ko5pkvojd3kjfq/node_modules/@neo4j/graphql/dist/schema/resolvers/query/root-connection.js:38:64)",
            "    at Object.organizationsConnection (/Users/litewarp/Projects/tltf/node_modules/.pnpm/@neo4j+graphql@3.3.0_iwp6h2plez23ko5pkvojd3kjfq/node_modules/@neo4j/graphql/dist/schema/resolvers/wrapper.js:65:12)",
            "    at executeField (/Users/litewarp/Projects/tltf/node_modules/.pnpm/graphql@16.5.0/node_modules/graphql/execution/execute.js:481:20)",
            "    at executeFields (/Users/litewarp/Projects/tltf/node_modules/.pnpm/graphql@16.5.0/node_modules/graphql/execution/execute.js:413:20)",
            "    at executeOperation (/Users/litewarp/Projects/tltf/node_modules/.pnpm/graphql@16.5.0/node_modules/graphql/execution/execute.js:344:14)",
            "    at execute (/Users/litewarp/Projects/tltf/node_modules/.pnpm/graphql@16.5.0/node_modules/graphql/execution/execute.js:136:20)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
The issue is that this line expects sortInput to be an array and not null or undefined: https://github.com/neo4j/graphql/blob/e1fda9fb14f533652a3e7437733352f114daa2ac/packages/graphql/src/translate/create-projection-and-params.ts#L333

The solution is to check for existence of sortInput in the if statement, or to set sortInput to default to an empty array.

Will submit a PR later to fix.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.
