### ISSUE TITLE
Nested Relations Error

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#2022]
This bug report is based on the dev branch from earlier today, including the PRs by @angrykoala so not sure if this is a bug on the current 3.7.0 package as well. 

I was giving the fix to #1536 a try to see if some of the interface queries that I had which were failing would be fixed. The good news is that many of them passed. But I think I found a new one, or at least a use case where the fix might not be sufficient. 

Long story short, I'm getting a similar error to #1536 where a nested type that implements the node interface does not end up included down the line in a cypher statement and throws. I wrote a failing test (below) and am also attaching the full stack trace of the test so you can see the cypher.

```typescript
// Failing Test
import type { GraphQLSchema } from "graphql";
import { graphql } from "graphql";
import type { Driver, Session } from "neo4j-driver";
import Neo4j from "../neo4j";
import { Neo4jGraphQL } from "../../../src";
import { generateUniqueType } from "../../utils/graphql-types";

describe("https://github.com/neo4j/graphql/issues/1536_2", () => {
    let schema: GraphQLSchema;
    let neo4j: Neo4j;
    let driver: Driver;
    let session: Session;

    const ArtPiece = generateUniqueType("ArtItem");
    const AuctionItem = generateUniqueType("Auction");
    const Organization = generateUniqueType("Organization");

    async function graphqlQuery(query: string) {
        return graphql({
            schema,
            source: query,
            contextValue: neo4j.getContextValues(),
        });
    }

    beforeAll(async () => {
        neo4j = new Neo4j();
        driver = await neo4j.getDriver();

        const typeDefs = `
            type ${ArtPiece} {
                dbId: ID! @id(global: true) @alias(property: "id")
                title: String!
                auction: ${AuctionItem} @relationship(type: "SOLD_AT_AUCTION_AS", direction: OUT)
                owner: ${Organization} @relationship(type: "OWNED_BY", direction: OUT)
            }
            type ${AuctionItem} {
                dbId: ID! @id(global: true) @alias(property: "id")
                auctionName: String!
                lotNumber: Int!
                item: ${ArtPiece}! @relationship(type: "SOLD_AT_AUCTION_AS", direction: IN)
                buyer: ${Organization}! @relationship(type: "BOUGHT_ITEM_AT_AUCTION", direction: IN)
                seller: ${Organization}! @relationship(type: "SOLD_ITEM_AT_AUCTION", direction: IN)
            }
            type ${Organization} {
                dbId: ID! @id(global: true) @alias(property: "id")
                name: String!
                artCollection: [${ArtPiece}!]! @relationship(type: "OWNED_BY", direction: IN)
                itemsSoldAtAuction: [${AuctionItem}!]! @relationship(type: "SOLD_ITEM_AT_AUCTION", direction: OUT)
                itemsBoughtAtAuction: [${AuctionItem}!]! @relationship(type: "BOUGHT_ITEM_AT_AUCTION", direction: OUT)
            }
        `;

        session = await neo4j.getSession();

        const neoGraphql = new Neo4jGraphQL({ typeDefs, driver });
        schema = await neoGraphql.getSchema();
    });

    afterAll(async () => {
        await session.close();
        await driver.close();
    });

    test("should not throw error when querying nested interfaces", async () => {
        const query = `
            query {
                ${ArtPiece.operations.connection} {
                    totalCount
                    edges {
                        node {
                            id
                            title
                            auction {
                                id
                                auctionName
                                lotNumber
                                buyer {
                                    id
                                    name
                                }
                            } 
                            owner {
                                id
                                name
                            }
                        }
                    }
                }
            }
        `;

        const queryResult = await graphqlQuery(query);
        expect(queryResult.errors).toBeUndefined();
    });
});
```

```
// Stack Trace

@neo4j/graphql:graphql Incoming GraphQL:
Query:
{
  sDftjGevArtItemsConnection {
    totalCount
    edges {
      node {
        id
        title
        auction {
          id
          auctionName
          lotNumber
          buyer {
            id
            name
          }
        }
        owner {
          id
          name
        }
      }
    }
  }
}
Variables:
{}
2022-09-02T00:52:56.835Z @neo4j/graphql:auth Could not get .req or .request from context
2022-09-02T00:52:56.836Z @neo4j/graphql:execute About to execute Cypher:
Cypher:
CALL dbms.components() YIELD versions, edition UNWIND versions AS version RETURN version, edition
Params:
{}
2022-09-02T00:52:56.896Z @neo4j/graphql:execute About to execute Cypher:
Cypher:
CALL {
MATCH (this:`sDFTJGevArtItem`)
WITH COLLECT(this) as edges
WITH edges, size(edges) as totalCount
UNWIND edges as this
WITH this, totalCount, { } as edges
RETURN this, totalCount, edges
}
WITH COLLECT({ node: this { .title, auction: this_auction, owner: this_owner, dbId: this.id } }) as edges, totalCount
RETURN { edges: edges, totalCount: totalCount } as this
Params:
{}
2022-09-02T00:52:56.918Z @neo4j/graphql:execute Neo4jError: Variable `this_auction` not defined (line 9, column 46 (offset: 239))
"WITH COLLECT({ node: this { .title, auction: this_auction, owner: this_owner, dbId: this.id } }) as edges, totalCount"
                                              ^
: 
    at captureStacktrace (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/result.js:239:17)
    at new Result (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/result.js:59:23)
    at newCompletedResult (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/transaction.js:433:12)
    at Object.run (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/transaction.js:287:20)
    at Transaction.Object.<anonymous>.Transaction.run (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/transaction.js:137:34)
    at Executor.transactionRun (/Users/litewarp/projects/graphql/packages/graphql/src/classes/Executor.ts:222:28)
    at /Users/litewarp/projects/graphql/packages/graphql/src/classes/Executor.ts:204:25
    at TransactionExecutor.Object.<anonymous>.TransactionExecutor._safeExecuteTransactionWork (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)
    at TransactionExecutor.Object.<anonymous>.TransactionExecutor._executeTransactionInsidePromise (/Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)
    at /Users/litewarp/projects/graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19 {
  constructor: [Function: Neo4jError],
  code: 'Neo.ClientError.Statement.SyntaxError'
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @litewarp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Thanks @litewarp I'll tale a look today

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
