### ISSUE TITLE
Query fails when query array of spatial type Point

### ISSUE THREAD

**Issue by revozhang** [neo4j/graphql#220]
**Describe the bug**
Query fails when query array of spatial type Point

**Type definitions**
~~~
type Asset {
  id: ID
  name: String
  coordinates: [Point]
}
~~~

**To Reproduce**
- create 
~~~
mutation {
  createAssets(
    input: {
      name: "test"
      coordinates: [
        { latitude: 31, longitude: 121 }
        { latitude: 31, longitude: 122 }
      ]
    }
  ) {
    assets {
      name
    }
  }
}
~~~
- query
~~~
{
  assets(where: { name: "test" }) {
    name
    coordinates {
      longitude
      latitude
    }
  }
}
~~~
- error message
~~~
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Point.longitude.",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "assets",
        0,
        "coordinates",
        0,
        "longitude"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Point.longitude.",
            "    at completeValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:559:13)",
            "    at resolveField (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:590:12)",
            "    at /home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:620:25",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at completeListValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:607:53)"
          ]
        }
      }
    },
    {
      "message": "Cannot return null for non-nullable field Point.longitude.",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "assets",
        0,
        "coordinates",
        1,
        "longitude"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Point.longitude.",
            "    at completeValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:559:13)",
            "    at resolveField (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:590:12)",
            "    at /home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:620:25",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at completeListValue (/home/lizhang/codebase/rthink/api_gateway/node_modules/graphql/execution/execute.js:607:53)"
          ]
        }
      }
    }
  ],
  "data": {
    "assets": [
      {
        "name": "test",
        "coordinates": [
          null,
          null
        ]
      }
    ]
  }
}
~~~

**Expected behavior**
Return array of points without issues.

**Additional context**
Query successful with neo4j-graphql-js

**Comment by darrellwarde** [comment]
Well that's awfully strange, we have an array of integration test cases using point arrays! 🤔  You're saying that type definitions with the single type `Asset` can be used to replicate this? If so, I'll see if I can replicate on my side and look into it! Thanks for raising. 🙂

**Comment by revozhang** [comment]
I started with a clean slate and it seems to be working now. Strange, must be old data in Neo4j. Thanks!
