### ISSUE TITLE
Can't change a seen value

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#225]
Raised by @tlester in Discord.

**To Reproduce**

The following query:

```graphql
query GetTimeline($profileID: ID) {
  posts(
    where: {
      OR: [
        {author: {
          inRelationship: {
            hasFriends: {
              hasProfiles: {id: $profileID}
            }
          }
        }},
        {hasComments: {
          author: {
            inRelationship: {
              hasFriends: {
                hasProfiles: {id: $profileID}
              }
            }
          }
        }}
      ]
    }
  ) {
      id
  }
}
```

Produces the following Cypher:

```
MATCH (this:Post)
WHERE (EXISTS((this)<-[:HAS_POST]-(:User)) AND ANY(this_OR_author IN [(this)<-[:HAS_POST]-(this_OR_author:User) | this_OR_author] WHERE EXISTS((this_OR_author)<-[:HAS_USER]-(:Profile)) AND ANY(this_OR_author_inRelationship IN [(this_OR_author)<-[:HAS_USER]-(this_OR_author_inRelationship:Profile) | this_OR_author_inRelationship] WHERE EXISTS((this_OR_author_inRelationship)-[:HAS_FRIEND]->(:Friend)) AND ANY(this_OR_author_inRelationship_hasFriends IN [(this_OR_author_inRelationship)-[:HAS_FRIEND]->(this_OR_author_inRelationship_hasFriends:Friend) | this_OR_author_inRelationship_hasFriends] WHERE EXISTS((this_OR_author_inRelationship_hasFriends)<-[:HAS_FRIEND]-(:Profile)) AND ANY(this_OR_author_inRelationship_hasFriends_hasProfiles IN [(this_OR_author_inRelationship_hasFriends)<-[:HAS_FRIEND]-(this_OR_author_inRelationship_hasFriends_hasProfiles:Profile) | this_OR_author_inRelationship_hasFriends_hasProfiles] WHERE this_OR_author_inRelationship_hasFriends_hasProfiles.id = $this_OR_author_inRelationship_hasFriends_hasProfiles_id)))) OR EXISTS((this)-[:HAS_COMMENT]->(:Comment)) AND ANY(this_OR1_hasComments IN [(this)-[:HAS_COMMENT]->(this_OR1_hasComments:Comment) | this_OR1_hasComments] WHERE EXISTS((this_OR1_hasComments)<-[:HAS_COMMENT]-(:User)) AND ANY(this_OR1_hasComments_author IN [(this_OR1_hasComments)<-[:HAS_COMMENT]-(this_OR1_hasComments_author:User) | this_OR1_hasComments_author] WHERE EXISTS((this_OR1_hasComments_author)<-[:HAS_USER]-(:Profile)) AND ANY(this_OR1_hasComments_author_inRelationship IN [(this_OR1_hasComments_author)<-[:HAS_USER]-(this_OR1_hasComments_author_inRelationship:Profile) | this_OR1_hasComments_author_inRelationship] WHERE EXISTS((this_OR1_hasComments_author_inRelationship)-[:HAS_FRIEND]->(:Friend)) AND ANY(this_OR1_hasComments_author_inRelationship_hasFriends IN [(this_OR1_hasComments_author_inRelationship)-[:HAS_FRIEND]->(this_OR1_hasComments_author_inRelationship_hasFriends:Friend) | this_OR1_hasComments_author_inRelationship_hasFriends] WHERE EXISTS((this_OR1_hasComments_author_inRelationship_hasFriends)<-[:HAS_FRIEND]-(:Profile)) AND ANY(this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles IN [(this_OR1_hasComments_author_inRelationship_hasFriends)<-[:HAS_FRIEND]-(this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles:Profile) | this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles] WHERE this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles.id = $this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles_id))))))
RETURN this { .id } as this
```

And the following Cypher params:

```
{  "this_OR_author_inRelationship_hasFriends_hasProfiles_id": "2ndact",  "this_OR1_hasComments_author_inRelationship_hasFriends_hasProfiles_id": "2ndact"}
```

When run through the JavaScript driver, this produces the following stack trace:

```
Neo4jError: Can't change a seen value
    at captureStacktrace (/app/node_modules/neo4j-driver/lib/result.js:281:15)    at new Result (/app/node_modules/neo4j-driver/lib/result.js:68:19)    at newCompletedResult (/app/node_modules/neo4j-driver/lib/transaction.js:455:10)    at Object.run (/app/node_modules/neo4j-driver/lib/transaction.js:289:14)    at Transaction.run (/app/node_modules/neo4j-driver/lib/transaction.js:125:32)    at /app/node_modules/@neo4j/graphql/dist/utils/execute.js:63:108    at TransactionExecutor._safeExecuteTransactionWork (/app/node_modules/neo4j-driver/lib/internal/transaction-executor.js:134:22)    at TransactionExecutor._executeTransactionInsidePromise (/app/node_modules/neo4j-driver/lib/internal/transaction-executor.js:122:32)    at /app/node_modules/neo4j-driver/lib/internal/transaction-executor.js:61:15    at new Promise (&lt;anonymous&gt;) {  code: 'Neo.DatabaseError.Statement.ExecutionFailed'}
```

The same error occurs when running the Cypher in Browser.

**Comment by tlester** [comment]
Looks like this is happening only when the where statement involves a nested relationship.   For example:

```
query Search($search: String) {
  profiles(
    where: {
      OR: [
        { displayName_MATCHES: $search }
        { tagline_MATCHES: $search }
        { bio_MATCHES: $search }
        { hasLocation: {name_MATCHES: $search}}
        { hasFriends: {hasProfiles: {displayName: $search}}}
      ]
    }
  ) {
    ...
}
```

That ^^^ breaks... but take that `hasFriends` out, which is a two hop relationship, it works.   I.e.:

```
query Search($search: String) {
  profiles(
    where: {
      OR: [
        { displayName_MATCHES: $search }
        { tagline_MATCHES: $search }
        { bio_MATCHES: $search }
        { hasLocation: {name_MATCHES: $search}}
      ]
    }
  ) {
    ...
}
```

That works fine.   FYI...  `hasLocation` is a relationship.  So, it works on relationships... just not relationships of relationship.

**Comment by darrellwarde** [comment]
It sounds like this is actually a bug in the Cypher runtime - it was been captured by that team and I will update this ticket as work progresses there.

**Comment by loveleif** [comment]
Sorry for the delay, but a fix has been merged now (except for version 4.1, still waiting for it to build, but will merge later today most probably). The fix will be included in the next release of 4.3, 4.2 and 4.1.

**Comment by tlester** [comment]
@loveleif -  I understand this is a cypher issue.  Has this fix been deployed to Aura?  If not, when do you think it'll happen?

**Comment by darrellwarde** [comment]
Closing this particular issue as resolved, as release progress can be followed at https://github.com/neo-technology/neo4j/pull/10771.

**Comment by tlester** [comment]
I'm not sure if this is fixed or not.  I can't seem to get a clear answer on the status of this being deployed or not into Aura.   It's pretty frustrating.   I want to be patient, but being completely blind to its implementation, I don't know if it's still broken or just not integrated into Aura.   @darrellwarde Is there any way we can verify this?  I *really* need to move on from this but am blind.
