### ISSUE TITLE
Bug on the allow direction which generates a forbidden error with the "limit" property

### ISSUE THREAD

**Issue by marth154** [neo4j/graphql#2741]
#OS: Windows and macOs
Version: @neo4j/graphql@3.10.1
Node.js version: 14.20.1
​
To secure my Neo4J database I use the "allow" directive on labels, in order to compare the owner ID and the current authenticated user ID.
​
However when I use "limit" and "offset" in a query I end up with a "Forbidden" error. By removing the "limit" property it works well.
​
Limiting the result set should'nt be more restricted that fetching the full set.
​
## Steps to reproduce
​
Use thise simple sample files:
​​
### The query causing the issue
```
  query Query($options: ApplicationOptions) {
    applications(options: $options) {
      id
      name
    }
  }
 variable: {
    "options": {
        "limit": 10
    }
}
```
​
### The schema 
```
  type Application {
    id: ID! @id(autogenerate: true)
    name: String!
    manageBy: Student! @relationship(type: "MANAGE", properties: "ManageProps", direction: IN)
  }
  extend type Application
    @auth(
      rules: [
        {
          isAuthenticated: true
          roles: ["Student"]
          allow: { manageBy: { id: "$jwt.id" } }
        }
      ]
    )
```
​
### The result: 
```
{
    "errors": [
        {
            "message": "Forbidden",
            "locations": [
                {
                    "line": 3,
                    "column": 5
                }
            ],
            "path": [
                "applications"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Neo4jGraphQLForbiddenError: Forbidden",
                        "    at Executor.formatError (D:\\Grimp\\grimp-api\\node_modules\\@neo4j\\graphql\\src\\classes\\Executor.ts:128:24)",
                        "    at Executor.execute (D:\\Grimp\\grimp-api\\node_modules\\@neo4j\\graphql\\src\\classes\\Executor.ts:121:24)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
                        "    at async execute (D:\\Grimp\\grimp-api\\node_modules\\@neo4j\\graphql\\src\\utils\\execute.ts:45:20)",
                        "    at async resolve (D:\\Grimp\\grimp-api\\node_modules\\@neo4j\\graphql\\src\\schema\\resolvers\\query\\read.ts:35:31)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```
## Workaround​
​
A workaround is to use "where" directive instead of allow.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @marth154. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @marth154 

A couple of questions:
* Is happening on an empty database? or are you receiving actual data when the not using the limit?
* Is the problem that your request should fail in both cases or it it is authenticated and failing where it shouldn't?

**Comment by marth154** [comment]
@angrykoala 
This problem appears on a database with data in it. 
The problem occurs on a query that should work and does not, but with the "limit" property it does not. 
And the person making the query is authenticated and it still fails

**Comment by angrykoala** [comment]
Thanks for the information @marth154, I'll try to replicate it

**Comment by angrykoala** [comment]
Hi @marth154 

Sadly I couldn't reproduce this problem.

I tried to reproduce as follows, as the provided information was not complete:

**Schema**

```graphql
type Application {
    id: ID! @id(autogenerate: true)
    name: String!
    manageBy: Student! @relationship(type: "MANAGE", properties: "ManageProps", direction: IN)
}

type Student {
    id: ID! @id(autogenerate: true)
}

interface ManageProps @relationshipProperties {
    year: Int
}

extend type Application
    @auth(rules: [{ isAuthenticated: true, roles: ["Student"], allow: { manageBy: { id: "$jwt.id" } } }])
```

**jwt payload**

```json
{
  "sub": "1234567890",
  "id": 1234,
  "roles": ["Student"]
}
```

**Dataset**
```cypher
CREATE(a:Application {id: "test", name: "app"})<-[:MANAGE]-(:Student {id: 1234})
```

**Queries**
```graphql
query Applications {
  applications{
    id
    name
  }
}

query Applications {
  applications(options: {limit: 10}) {
    id
    name
  }
}
```

Tried with both, 3.14.2 and 3.10.1 versions of `@neo4j/graphql`

With both queries, the request was successful with the given payload and failed if the payload didn't fulfil auth rules.

I'll close this as we were not able to reproduce it, please, feel free to provide extra information that may help us to reproduce this, like the jwt payload and dataset in your database and I'll reopen it if we are able to reproduce it.
Also, if possible, use the latest version of `@neo4j/graphql` .
