### ISSUE TITLE
Optional variables not working inside NOT operator

### ISSUE THREAD

**Issue by mikaelmattsson** [neo4j/graphql#3215]
When i try a query like this

```graphql
query MyQuery($name: String) {
  actors(
    where: {
      age_GT: 25,
      NOT: {name: $name}
    }
  ) {
    name
    age
  }
}
```

If $name is not set i get this error

```
TypeError: Cannot read properties of undefined (reading 'getCypher')
    at NotOp.getCypher (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/expressions/operations/boolean.js:61:37)
    at /app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/expressions/operations/boolean.js:44:57
    at Array.map (<anonymous>)
    at BinaryOp.getCypher (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/expressions/operations/boolean.js:44:44)
    at /app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/expressions/operations/boolean.js:44:57
    at Array.map (<anonymous>)
    at BinaryOp.getCypher (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/expressions/operations/boolean.js:44:44)
    at Where.getCypher (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/clauses/sub-clauses/Where.js:36:43)
    at compileCypherIfExists (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/utils/compile-cypher-if-exists.js:26:28)
    at Match.getCypher (/app/node_modules/.pnpm/@neo4j+cypher-builder@0.2.1/node_modules/@neo4j/cypher-builder/dist/clauses/Match.js:92:82)
```

I kind of expect this to work the same as the old, now deprecated, syntax:

```graphql
query MyQuery($name: String) {
  actors(
    where: {
      age_GT: 25,
      name_NOT: $name
    }
  ) {
    name
    age
  }
}
```

In this case it would not filter by name at all.
I like the new way of doing negation because it will make the schema so much smaller when the old way is removed. :+1:

* Version: tested with @neo4j/graphql@3.17.0, @neo4j/graphql@3.17.2, @neo4j/graphql@3.18.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mikaelmattsson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mikaelmattsson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Related to #236
