### ISSUE TITLE
Relationship properties - connection variable not defined

### ISSUE THREAD

**Issue by aitor3ml** [neo4j/graphql#369]
**Describe the bug**
Variable not defined error when trying to request relationship properties (using interface).

**Type definitions**
```
type Dato {
  uuid: ID
  dependeTo : [Dato] @relationship(type: "DEPENDE", direction: OUT, properties: "Depende")
  dependeFrom : [Dato] @relationship(type: "DEPENDE", direction: IN, properties: "Depende")
}

interface Depende {
  uuid: ID
  variable: String
}

type Query {
  getDato(uuid: String): Dato
    @cypher(
      statement: """
        MATCH (d:Dato {uuid: $uuid}) RETURN d
        """
    )
}
```

**To Reproduce**
1. Run a server with the previous graphql schema
2. Execute the following Query
This will work correctly.
```
{
  getDato(uuid:"4ebd5854-9caf-403f-bc96-f23f1a39e83d"){
    uuid
    dependeTo {
        uuid
      dependeFrom {
        uuid
      }      
    }
  }
}
```

3. Then run the following Query
This will return error.
```
{
  getDato(uuid:"4ebd5854-9caf-403f-bc96-f23f1a39e83d"){
    uuid
    dependeToConnection {
      edges {
        uuid
        variable
      }
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Variable `dependeToConnection` not defined (line 6, column 22 (offset: 223))\n\"RETURN this { .uuid, dependeToConnection } AS this\"\n                      ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getDato"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.SyntaxError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Variable `dependeToConnection` not defined (line 6, column 22 (offset: 223))",
            "\"RETURN this { .uuid, dependeToConnection } AS this\"",
            "                      ^",
            ": ",
            "    at captureStacktrace (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/result.js:239:17)",
            "    at new Result (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/result.js:59:23)",
            "    at newCompletedResult (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:372:12)",
            "    at Object.run (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:226:20)",
            "    at Transaction.run (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:98:34)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/src/utils/execute.ts:88:16",
            "    at TransactionExecutor._safeExecuteTransactionWork (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19",
            "    at new Promise (<anonymous>)",
            "    at TransactionExecutor.execute (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:39:16)",
            "    at Session._runTransaction (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/session.js:305:42)",
            "    at Session.writeTransaction (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/session.js:301:21)",
            "    at Object.<anonymous> (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/src/utils/execute.ts:87:92)",
            "    at Generator.next (<anonymous>)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/dist/utils/execute.js:26:71"
          ]
        }
      }
    }
  ],
  "data": {
    "getDato": null
  }
}
```

**Expected behavior**
Is expected to receive the variable property for each relationship "DEPENDE".

**System (please complete the following information):**

-   OS: Debian 10
-   Version: 2.0.0-alpha.4
-   Node.js version: v14.16.0

**Additional context**

- In neo4j-graphql-js this query failed when relationships when from and to the same label (in this case (:Dato)-[]->(:Dato) but in this case fails even when this are different.
- When only one direction is defined the query also fails.
- Cypher Debug:
```
@neo4j/graphql:execute About to execute Cypher:
Cypher:

                WITH apoc.cypher.runFirstColumn("MATCH (d:Dato {uuid: $uuid}) RETURN d", {auth: $auth, uuid: $uuid}, false) as x
                UNWIND x as this
                WITH this
            
RETURN this { .uuid, dependeToConnection } AS this
Params:
{
  "uuid": "4ebd5854-9caf-403f-bc96-f23f1a39e83d",
  "auth": {
    "isAuthenticated": false,
    "roles": []
  }
} +4s
  @neo4j/graphql:execute Neo4jError: Variable `dependeToConnection` not defined (line 6, column 22 (offset: 223))
```

**Comment by darrellwarde** [comment]
Thanks @aitor3ml, we'll look into it! 🙂

**Comment by aitor3ml** [comment]
@darrellwarde thank you for you fast response.
Btw, any idea when you will release a new version including this fix (alpha)?
We are finishing the migration from neo4j-graphql-js and trying to continue our product development using this library.
Hopefully we will be able to migrate all of our clients to an stable release in our product's next milestone.

**Comment by darrellwarde** [comment]
Hey @aitor3ml, obviously no promises, but we're aiming to do the next release this afternoon (UK time). 🙂

**Comment by danstarns** [comment]
Hey, @aitor3ml download the latest next version for the update https://www.npmjs.com/package/@neo4j/graphql/v/2.0.0-rc.1  Have a nice day :)

**Comment by aitor3ml** [comment]
Worked like a charm (2.0.0-rc.1), thank you once again!
![image](https://user-images.githubusercontent.com/12745799/127678234-4703f426-1ea0-462f-bdcc-2f93d7e46cb6.png)
