### ISSUE TITLE
GraphQLError: The directive "@authentication" can only be used once at this location.

### ISSUE THREAD

**Issue by mathix420** [neo4j/graphql#3746]
**Describe the bug**
Getting an error when using `@authentication` for a specific query.

```
[
  GraphQLError: The directive "@authentication" can only be used once at this location.
      at Object.enter (/home/mathix/projects/peach_api/node_modules/graphql/validation/rules/UniqueDirectivesPerLocationRule.js:81:15)
      at Object.enter (/home/mathix/projects/peach_api/node_modules/graphql/language/visitor.js:301:32)
      at visit (/home/mathix/projects/peach_api/node_modules/graphql/language/visitor.js:197:21)
      at validateSDL (/home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/schema/validation/validate-sdl.ts:38:10)
      at validateUserDefinition (/home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/schema/validation/schema-validation.ts:106:31)
      at /home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/classes/Neo4jGraphQL.ts:334:39
      at new Promise (<anonymous>)
      at Neo4jGraphQL.generateExecutableSchema (/home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/classes/Neo4jGraphQL.ts:312:16)
      at Neo4jGraphQL.getExecutableSchema (/home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/classes/Neo4jGraphQL.ts:116:42)
      at Neo4jGraphQL.getSchema (/home/mathix/projects/peach_api/node_modules/@neo4j/graphql/src/classes/Neo4jGraphQL.ts:111:21) {
    path: undefined,
    locations: [ [Object] ],
    extensions: [Object: null prototype] {}
  }
]
```

**Type definitions**
```graphql
type Query {
    checkLogin: Boolean! @authentication
}
```

**To Reproduce**

1. Basic server following tutorial on Neo4j

Versions:
```
    "@apollo/server": "^4.9.1",
    "@neo4j/graphql": "^4.0.0-beta.1",
    "@neo4j/graphql-ogm": "^4.0.0-beta.1",
    "neo4j-driver": "^5.11.0",
    "graphql": "^16.7.1",
    "graphql-tag": "^2.12.6",
```

**Expected behavior**
Should do the authentication.

**System (please complete the following information):**

* OS: archlinux
* Version: @neo4j/graphql@4.0.0-beta.1 (also tested with latest v3)
* Node.js version: v18.16.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mathix420** [comment]
The issue seems to appear only when fields are not handled by neo4j.

For example this seems to work fine:
```graphql
type Query {
    checkLogin: Boolean! @authentication @cypher(statement: "RETURN true as res", columnName: "res")
    me: String! @authentication @cypher(statement: "RETURN 'hello' as res", columnName: "res")
}
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
Bit of a weird one, I'm taking a look now!

**Comment by darrellwarde** [comment]
Okay, I've found the issue. However, the gist of this is that `@authentication` can only be used on root query/mutation fields with the `@cypher` directive. `@authentication` is evaluated during the translation phase of the request, and for a query field in this scenario, no translation takes place and thus it can't be evaluated. I'll be adding an error message for this scenario.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
On reflection, we could add another simple wrapper using resolver composition to perform this authentication checks only.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.
