### ISSUE TITLE
Enum default value does not work for certain values

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#3912]
**Describe the bug**
In 4.1.1 it seems like PRIVATE and PUBLIC can't be used as default values. It works with VISIBLE and PRIVATE2 so I think they seem to be reserved keywords or something like that.

I get the following error:

```
Error Starting Server
[
  GraphQLError: @default.value on EventPrivacy fields must be of type EventPrivacy
      at createGraphQLError (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\custom-rules\utils\document-validation-error.js:36:12)
      at Object.Directive (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\custom-rules\directives\valid-directive.js:79:92)
      at Object.enter (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:301:32)
      at visit (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:197:21)
      at validateSDL (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-sdl.js:32:25)
      at runValidationRulesOnFilteredDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:177:51)
      at validateDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:219:5)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:267:51
      at new Promise (<anonymous>)
      at Neo4jGraphQL.generateExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:263:16)
      at Neo4jGraphQL.getExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:89:42)
      at Neo4jGraphQL.getSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:85:21)
      at Object.<anonymous> (C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\server.js:75:50)
      at Generator.next (<anonymous>)
      at fulfilled (C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\server.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    path: [ 'Event', 'privacy', '@default', 'value' ],
    locations: undefined,
    extensions: [Object: null prototype] {}
  }
]
```

**Type definitions**
```
 enum EventPrivacy {
    PRIVATE
    VISIBLE
    PUBLIC
  }
  
  type Event {
    id: ID! @id
    name: String!
    # The Privacy for the Event --> See Enum
    privacy: EventPrivacy @default(value: PRIVATE)
    }
```

**Expected behavior**
PRIVATE and PUBLIC should be usable since they are very common among enums.

I am just back from vacation and will have a look at the unreproducible #3771 in the next few days.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hi @eriklueth, I'm afraid once again that I can't reproduce this. I have even added an integration test which you're welcome to look at in #3915. Feel free to give more context, but this feels like it possibly isn't an issue with the library itself. Thanks!

**Comment by darrellwarde** [comment]
Please ignore the above, it would seem that the GraphQL Toolbox has fallen out of date. Going to review both of these things.

**Comment by darrellwarde** [comment]
This one is still very much the case, I can't reproduce.

**Comment by darrellwarde** [comment]
Feel free to reopen if you want to provide steps to reproduce.
