### ISSUE TITLE
Multiple relationship connection query - connection variable not defined

### ISSUE THREAD

**Issue by aitor3ml** [neo4j/graphql#399]
**Describe the bug**
Error thrown when trying to request more than one relationship connection field.
It works fine when requesting for multiple connections in nested fields, but not at root level.

**Type definitions**
```
type Dato @exclude {
  uuid: ID
  dependeTo : [Dato] @relationship(type: "DEPENDE", direction: OUT, properties: "Depende")
  dependeFrom : [Dato] @relationship(type: "DEPENDE", direction: IN, properties: "Depende")
  entradas : [Source] @relationship(type: "ENTRADA", direction: IN, properties: "Entrada")
}

interface Depende {
  uuid: ID
  variable: String
}

type Source @exclude {
  uuid: ID
  modelo: String
}

interface Entrada {
  uuid: ID
  topic: String
}

type Query {
  getDato(uuid: String): Dato @auth(rules: [{ isAuthenticated: true }]) @auth(rules: [{ operations: [UPDATE], roles: ["admin"] }])
    @cypher(
      statement: """
        MATCH (d:Dato {uuid: $uuid})
        RETURN d
        """
    )
}
```

**To Reproduce**

1. Run a server with the previous schema
2. Execute the following Query:
```
{
  getDato(uuid:"4ebd5854-9caf-403f-bc96-f23f1a39e83d"){
    uuid
    dependeToConnection {
      totalCount
    }
    dependeFromConnection {
      totalCount
    }    
    entradasConnection {
      totalCount
    }
  }
}
```
3. See error
```
{
  "errors": [
    {
      "message": "Variable `dependeToConnection` not defined (line 14, column 22 (offset: 550))\n\"RETURN this { .uuid, dependeToConnection, dependeFromConnection, entradasConnection } AS this\"\n                      ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getDato"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.SyntaxError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Variable `dependeToConnection` not defined (line 14, column 22 (offset: 550))",
            "\"RETURN this { .uuid, dependeToConnection, dependeFromConnection, entradasConnection } AS this\"",
            "                      ^",
            ": ",
            "    at captureStacktrace (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/result.js:239:17)",
            "    at new Result (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/result.js:59:23)",
            "    at newCompletedResult (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:372:12)",
            "    at Object.run (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:226:20)",
            "    at Transaction.run (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/transaction.js:98:34)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/src/utils/execute.ts:88:16",
            "    at TransactionExecutor._safeExecuteTransactionWork (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19",
            "    at new Promise (<anonymous>)",
            "    at TransactionExecutor.execute (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:39:16)",
            "    at Session._runTransaction (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/session.js:305:42)",
            "    at Session.writeTransaction (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/neo4j-driver-core/lib/session.js:301:21)",
            "    at Object.<anonymous> (/home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/src/utils/execute.ts:87:92)",
            "    at Generator.next (<anonymous>)",
            "    at /home/amartin/projects/lynx/gits/lynx-backend/node_modules/@neo4j/graphql/dist/utils/execute.js:26:71"
          ]
        }
      }
    }
  ],
  "data": {
    "getDato": null
  }
}
```
**Expected behavior**
The response with data from multiple relationshipConnection.

**System:**

-   OS: Debian 10
-   Version: 2.0.0-rc.2
-   Node.js version: v14.16.0

**Additional context**
- Works correctly when only one connection field is requested (#369), 2 or more fail.
- Regular fields (relationships), when relationship properties are not needed, work fine.
- Works when requesting multiple connections fields in a nested (not root) object. Example:
```
{
  getDato(uuid:"4ebd5854-9caf-403f-bc96-f23f1a39e83d"){
    uuid
    dependeTo {
      dependeToConnection {
        totalCount
      }
      dependeFromConnection {
        totalCount
      }
    }
  }
}
```

**Comment by darrellwarde** [comment]
Hey @aitor3ml, sorry about this, it's fixed in #398.
