### ISSUE TITLE
Can't use custom Input Types in Object Types (Regression)

### ISSUE THREAD

**Issue by mathix420** [neo4j/graphql#4001]
**Describe the bug**
Can't use custom Input Types in Object Types.

**Type definitions**
```graphql
input Pagination {
    limit: Int = 20
    offset: Int = 0
}

type Video {
  id: ID!
}

type Serie {
  id: ID!

  allEpisodes(options: Pagination): [Video!]!
    @cypher(
        statement: """
        MATCH (n:Video) RETURN n
        SKIP toInteger($options.offset) LIMIT toInteger($options.limit)
        """
        columnName: "n"
    )
}
```

**To Reproduce**

1. Just running the type definitions will cause this error:
```
Error: Error while parsing Attribute with name: Pagination
    at parseTypeNode (REDACTED/node_modules/@neo4j/graphql/dist/schema-model/parser/parse-attribute.js:122:23)
    at REDACTED/node_modules/@neo4j/graphql/dist/schema-model/parser/parse-attribute.js:36:19
    at Array.map (<anonymous>)
    at parseAttributeArguments (REDACTED/node_modules/@neo4j/graphql/dist/schema-model/parser/parse-attribute.js:33:22)
    at parseAttribute (REDACTED/node_modules/@neo4j/graphql/dist/schema-model/parser/parse-attribute.js:46:18)
    at REDACTED/node_modules/@neo4j/graphql/dist/schema-model/generate-model.js:277:53
    at Array.map (<anonymous>)
    at generateConcreteEntity (REDACTED/node_modules/@neo4j/graphql/dist/schema-model/generate-model.js:263:46)
    at REDACTED/node_modules/@neo4j/graphql/dist/schema-model/generate-model.js:31:92
    at Array.map (<anonymous>)
REDACTED/node_modules/@neo4j/graphql/dist/schema-model/parser/parse-attribute.js:122
                throw new Error(`Error while parsing Attribute with name: ${typeNode.name.value}`);
                      ^
```

**Expected behavior**
Should not raise an error.

**System (please complete the following information):**

* OS: Arch Linux
* Version: @neo4j/graphql@4.1.2
* Node.js version: v18.16.1

**Additional context**
Was working well in 4.1.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
