### ISSUE TITLE
Error when performing nested authorization checks

### ISSUE THREAD

**Issue by GuyShane** [neo4j/graphql#4113]
### Type definitions

```GraphQL
type JWT @jwt {
	id: ID!
	email: String!
	roles: [String!]!
	store: ID
}

type User {
	id: ID! @id @unique
	email: String!
	roles: [String!]!
	store: Store @relationship(type: "WORKS_AT", direction: OUT)
}

type Store {
	id: ID! @id @unique
	name: String!
	employees: [User!]! @relationship(type: "WORKS_AT", direction: IN)
	transactions: [Transaction!]! @relationship(type: "TRANSACTION", direction: IN)
}

type Transaction {
	id: ID! @id @unique
	store: Store! @relationship(type: "TRANSACTION", direction: OUT)
	type: String!
	items: [TransactionItem!]! @relationship(type: "ITEM_TRANSACTED", direction: IN)
}

type TransactionItem {
	transaction: Transaction @relationship(type: "ITEM_TRANSACTED", direction: OUT)
	name: String
	price: Float
	quantity: Int
}

extend type Transaction @authentication
extend type Transaction
	@authorization(
		validate: [
			{
				operations: [CREATE, CREATE_RELATIONSHIP]
				where: {
					jwt: { OR: [{ roles_INCLUDES: "store-owner" }, { roles_INCLUDES: "employee" }] }
					node: { store: { id: "$jwt.store" } }
				}
			}
		]
	)

extend type TransactionItem @authentication
extend type TransactionItem
	@authorization(
		validate: [
			{
				operations: [CREATE, CREATE_RELATIONSHIP]
				where: {
					jwt: { OR: [{ roles_INCLUDES: "store-owner" }, { roles_INCLUDES: "employee" }] }
					node: { transaction: { store: { id: "$jwt.store" } } }
				}
			}
		]
	)
```

### Test data

```Shell
mutation CreateUsers {
  createUsers(input: [
    {email: "a@a.com", roles: "store-owner"},
    {email: "b@b.com", roles: "store-owner"}
  ]) {
    users {
      id
    }
  }
}

mutation CreateStores {
  createStores(input: [
    {
      name: "Store", 
      employees: {
        connect: {
          where: {
            node: {
              email: "a@a.com"
            }
          }
        }
      }
    },
    {
      name: "Other Store", 
      employees: {
        connect: {
          where: {
            node: {
              email: "b@b.com"
            }
          }
        }
      }
    }
  ]) {
    stores {
      id
      name
      employees {
        email
      }
    }
  }
}

query GetAuthInfo {
  users(where: {email: "a@a.com"}) {
    id
    email
    roles
    store {
      id
    }
  }
}

mutation CreateTransactionForMyStore {
  createTransactions(input: {
    type: "sale", 
    store: {
      connect: {
        where: {
          node: {
            name: "Store"
          }
        }
      }
    }
    items: {
      create: [
        {node: {name: "Milk", price: 2.50, quantity: 3}},
        {node: {name: "Eggs", price: 5.00, quantity: 1}}
      ]
    }
  }
) {
    transactions {
      store {
        name
      }
      items {
        name
      }
    }
  }
}

mutation CreateTransactionForOtherStore {
  createTransactions(input: {
    type: "sale", 
    store: {
      connect: {
        where: {
          node: {
            name: "Other Store"
          }
        }
      }
    }
    items: {
      create: [
        {node: {name: "Milk", price: 2.50, quantity: 3}},
        {node: {name: "Eggs", price: 5.00, quantity: 1}}
      ]
    }
  }
) {
    transactions {
      store {
        name
      }
      items {
        name
      }
    }
  }
}
```

### Steps to reproduce

1. Start server with JWT authorization enabled
2. Run CreateUsers and CreateStores mutations
3. Run either CreateTransactionForMyStore or CreateTransactionForOtherStore mutation with a JWT made using the output from GetAuthInfo

### What happened

The following error is returned:
```
Neo4jError: Variable `authorization_var0` already declared in outer scope (line 83, column 46 (offset: 3635)
```

### Expected behaviour

CreateTransactionFroMyStore should run successfully and CreateTransactionForOtherStore should throw an authorization error.

It runs successfully if I remove one of the `node` checks in the validation rules, but that no longer enforces the security I'm looking for.

### Version

4.3.2

### Database version

5.12.0

### Relevant log output

```Shell
Query:
mutation CreateTransactionForMyStore {
  createTransactions(
    input: {type: "sale", store: {connect: {where: {node: {name: "Store"}}}}, items: {create: [{node: {name: "Milk", price: 2.50, quantity: 3}}, {node: {name: "Eggs", price: 5.00, quantity: 1}}]}}
  ) {
    transactions {
      store {
        name
      }
      items {
        name
      }
    }
  }
}
Variables:
{}
2023-10-12T21:49:53.328Z @neo4j/graphql:auth Authorization header with authentication scheme 'Bearer <token>'
2023-10-12T21:49:53.329Z @neo4j/graphql:auth Verifying JWT using secret
2023-10-12T21:49:53.390Z @neo4j/graphql:execute About to execute Cypher:
Cypher:
CALL {
CREATE (this0:Transaction)
SET this0.id = randomUUID()
SET this0.type = $this0_type
WITH *
CALL {
	WITH this0
	OPTIONAL MATCH (this0_store_connect0_node:Store)
	WHERE this0_store_connect0_node.name = $this0_store_connect0_node_param0
	CALL {
		WITH *
		WITH collect(this0_store_connect0_node) as connectedNodes, collect(this0) as parentNodes
		CALL {
			WITH connectedNodes, parentNodes
			UNWIND parentNodes as this0
			UNWIND connectedNodes as this0_store_connect0_node
			MERGE (this0)-[:TRANSACTION]->(this0_store_connect0_node)
		}
	}
WITH this0, this0_store_connect0_node
WITH *
OPTIONAL MATCH (this0)-[:TRANSACTION]->(authorization_this0:Store)
WITH *, count(authorization_this0) AS storeCount
WITH *
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (($authorization_param1 IN $jwt.roles OR $authorization_param3 IN $jwt.roles) AND (storeCount <> 0 AND ($jwt.store IS NOT NULL AND authorization_this0.id = $jwt.store)))), "@neo4j/graphql/FORBIDDEN", [0])
	RETURN count(*) AS connect_this0_store_connect_Store0
}

WITH *
CREATE (this0_items0_node:TransactionItem)
SET this0_items0_node.name = $this0_items0_node_name
SET this0_items0_node.price = $this0_items0_node_price
SET this0_items0_node.quantity = $this0_items0_node_quantity
MERGE (this0)<-[:ITEM_TRANSACTED]-(this0_items0_node)
WITH *
CALL {
	WITH this0_items0_node
	MATCH (this0_items0_node)-[this0_items0_node_transaction_Transaction_unique:ITEM_TRANSACTED]->(:Transaction)
	WITH count(this0_items0_node_transaction_Transaction_unique) as c
	WHERE apoc.util.validatePredicate(NOT (c <= 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDTransactionItem.transaction must be less than or equal to one', [0])
	RETURN c AS this0_items0_node_transaction_Transaction_unique_ignored
}

WITH *
CREATE (this0_items1_node:TransactionItem)
SET this0_items1_node.name = $this0_items1_node_name
SET this0_items1_node.price = $this0_items1_node_price
SET this0_items1_node.quantity = $this0_items1_node_quantity
MERGE (this0)<-[:ITEM_TRANSACTED]-(this0_items1_node)
WITH *
CALL {
	WITH this0_items1_node
	MATCH (this0_items1_node)-[this0_items1_node_transaction_Transaction_unique:ITEM_TRANSACTED]->(:Transaction)
	WITH count(this0_items1_node_transaction_Transaction_unique) as c
	WHERE apoc.util.validatePredicate(NOT (c <= 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDTransactionItem.transaction must be less than or equal to one', [0])
	RETURN c AS this0_items1_node_transaction_Transaction_unique_ignored
}
WITH *
CALL {
	WITH this0
	MATCH (this0)-[this0_store_Store_unique:TRANSACTION]->(:Store)
	WITH count(this0_store_Store_unique) as c
	WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDTransaction.store required exactly once', [0])
	RETURN c AS this0_store_Store_unique_ignored
}
WITH *
CALL {
    WITH this0_items0_node
    MATCH (this0_items0_node)-[:ITEM_TRANSACTED]->(authorization_this1:Transaction)
    OPTIONAL MATCH (authorization_this1)-[:TRANSACTION]->(authorization_this2:Store)
    WITH *, count(authorization_this2) AS storeCount
    WITH *
    WHERE (storeCount <> 0 AND ($jwt.store IS NOT NULL AND authorization_this2.id = $jwt.store))
    RETURN count(authorization_this1) = 1 AS authorization_var0
}
CALL {
    WITH this0_items1_node
    MATCH (this0_items1_node)-[:ITEM_TRANSACTED]->(authorization_this1:Transaction)
    OPTIONAL MATCH (authorization_this1)-[:TRANSACTION]->(authorization_this2:Store)
    WITH *, count(authorization_this2) AS storeCount
    WITH *
    WHERE (storeCount <> 0 AND ($jwt.store IS NOT NULL AND authorization_this2.id = $jwt.store))
    RETURN count(authorization_this1) = 1 AS authorization_var0
}
OPTIONAL MATCH (this0)-[:TRANSACTION]->(authorization_this0:Store)
WITH *, count(authorization_this0) AS storeCount
WITH *
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (($authorization_param1 IN $jwt.roles OR $authorization_param3 IN $jwt.roles) AND authorization_var0 = true)), "@neo4j/graphql/FORBIDDEN", [0]) AND apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (($authorization_param1 IN $jwt.roles OR $authorization_param3 IN $jwt.roles) AND authorization_var0 = true)), "@neo4j/graphql/FORBIDDEN", [0]) AND apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (($authorization_param1 IN $jwt.roles OR $authorization_param3 IN $jwt.roles) AND (storeCount <> 0 AND ($jwt.store IS NOT NULL AND authorization_this0.id = $jwt.store)))), "@neo4j/graphql/FORBIDDEN", [0])
RETURN this0
}
CALL {
    WITH this0
    CALL {
        WITH this0
        MATCH (this0)-[create_this0:TRANSACTION]->(create_this1:Store)
        WITH create_this1 { .name } AS create_this1
        RETURN head(collect(create_this1)) AS create_var2
    }
    CALL {
        WITH this0
        MATCH (this0)<-[create_this3:ITEM_TRANSACTED]-(create_this4:TransactionItem)
        WITH create_this4 { .name } AS create_this4
        RETURN collect(create_this4) AS create_var5
    }
    RETURN this0 { store: create_var2, items: create_var5 } AS create_var6
}
RETURN [create_var6] AS data
Params:
{
  "this0_type": "sale",
  "this0_store_connect0_node_param0": "Store",
  "isAuthenticated": true,
  "authorization_param1": "store-owner",
  "jwt": {
    "sub": "1234567890",
    "name": "John Doe",
    "iat": 1516239022,
    "id": "7b19d2a2-17ae-4c0b-ab98-b73116f45cbe",
    "email": "a@a.com",
    "roles": [
      "store-owner"
    ],
    "store": "8b3f5c06-4d7e-479f-af63-ea744b06f62e"
  },
  "authorization_param3": "employee",
  "this0_items0_node_name": "Milk",
  "this0_items0_node_price": 2.5,
  "this0_items0_node_quantity": {
    "low": 3,
    "high": 0
  },
  "this0_items1_node_name": "Eggs",
  "this0_items1_node_price": 5,
  "this0_items1_node_quantity": {
    "low": 1,
    "high": 0
  },
  "resolvedCallbacks": {}
}
2023-10-12T21:49:53.838Z @neo4j/graphql:execute Neo4jError: Variable `authorization_var0` already declared in outer scope (line 83, column 46 (offset: 3635))
"    RETURN count(authorization_this1) = 1 AS authorization_var0"
                                              ^

    at captureStacktrace (/root/node_modules/neo4j-driver-core/lib/result.js:613:17)
    at new Result (/root/node_modules/neo4j-driver-core/lib/result.js:105:23)
    at newCompletedResult (/root/node_modules/neo4j-driver-core/lib/transaction.js:510:12)
    at Object.run (/root/node_modules/neo4j-driver-core/lib/transaction.js:342:20)
    at Transaction.run (/root/node_modules/neo4j-driver-core/lib/transaction.js:183:34)
    at ManagedTransaction.run (/root/node_modules/neo4j-driver-core/lib/transaction-managed.js:56:21)
    at Executor.transactionRun (/root/node_modules/@neo4j/graphql/dist/classes/Executor.js:162:28)
    at /root/node_modules/@neo4j/graphql/dist/classes/Executor.js:148:33
    at TransactionExecutor._safeExecuteTransactionWork (/root/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:213:26)
    at TransactionExecutor.<anonymous> (/root/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:200:46) {
  constructor: [Function],
  code: 'Neo.ClientError.Statement.SyntaxError',
  retriable: false
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @GuyShane. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @GuyShane. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @GuyShane! :pray: We will now prioritise the bug and address it appropriately.
