### ISSUE TITLE
Unhandled Errors in OGM Type Generation

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#4123]
**Describe the bug**
When generating OGM Types for a wrong schema I get the following console message:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

This gives developers no way to see what went wrong.

After some searching, it seems like it's coming from the createInitializer() Method in the OGM.js. 
By adding a catch statement developers can see what has gone wrong and can fix it.

```
    createInitializer() {
        return new Promise((resolve) => {
            console.log("OGM init");
            this.neoSchema.getSchema().then((schema) => {
                this._schema = schema;
                this.models.forEach((model) => this.initModel(model));
                resolve();
            }).catch((e) => {
                console.log("Error in OGM init", e);
            }
            )
        });
    }
```

New Console Output:
```
Error in OGM init [
  GraphQLError: Directive "@cypher" argument "columnName" of type "String!" is required, but it was not provided.
      at Object.leave (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\validation\rules\ProvidedRequiredArgumentsRule.js:143:17)
      at Object.leave (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:324:32)
      at visit (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:197:21)
      at validateSDL (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-sdl.js:32:25)
      at runValidationRulesOnFilteredDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:165:51)
      at validateDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:209:5)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:266:51
      at new Promise (<anonymous>)
      at Neo4jGraphQL.generateExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:262:16)
      at Neo4jGraphQL.getExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:90:42)
      at Neo4jGraphQL.getSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:86:21)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:111:28
      at new Promise (<anonymous>)
      at OGM.createInitializer (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:109:16)
      at OGM.init (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:67:37)
      at generate (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\generate.js:121:23)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\index.js:36:46
      at Generator.next (<anonymous>)
      at fulfilled (C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\index.js:8:58) {
    path: undefined,
    locations: undefined,
    extensions: [Object: null prototype] {}
  },
  GraphQLError: Directive "@cypher" argument "columnName" of type "String!" is required, but it was not provided.
      at Object.leave (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\validation\rules\ProvidedRequiredArgumentsRule.js:143:17)
      at Object.leave (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:324:32)
      at visit (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\graphql\language\visitor.js:197:21)
      at validateSDL (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-sdl.js:32:25)
      at runValidationRulesOnFilteredDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:165:51)
      at validateDocument (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\schema\validation\validate-document.js:209:5)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:266:51
      at new Promise (<anonymous>)
      at Neo4jGraphQL.generateExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:262:16)
      at Neo4jGraphQL.getExecutableSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:90:42)
      at Neo4jGraphQL.getSchema (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Neo4jGraphQL.js:86:21)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:111:28
      at new Promise (<anonymous>)
      at OGM.createInitializer (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:109:16)
      at OGM.init (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\OGM.js:67:37)
      at generate (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\generate.js:121:23)
      at C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\index.js:36:46
      at Generator.next (<anonymous>)
      at fulfilled (C:\Projekte\Dashpoint\dashpoint-graphql-backend\dist\index.js:8:58) {
    path: undefined,
    locations: undefined,
    extensions: [Object: null prototype] {}
  },....]
```

It would also be really great to add the file name where the error occurred to your error messages to make it easier for developers to debug.

Sorry for not coming back to the other issues from before. I was caught up in a lot of other work and now finally get back to working on the 4.0.0 transition... 😊

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @eriklueth! :pray: We will now prioritise the bug and address it appropriately.
