### ISSUE TITLE
Error: Cannot use GraphQLNonNull "String!" from another module or realm when attempting integration with NextJS and Apollo.

### ISSUE THREAD

**Issue by forsakendaemon** [neo4j/graphql#4297]
**Describe the bug**
When requesting a GraphQLSchema in a fresh NextJS project with Apollo Server, the following error is generated:

```
Error: Cannot use GraphQLNonNull "String!" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (webpack-internal:///(rsc)/./node_modules/graphql/jsutils/instanceOf.js:27:19)
    at isNonNullType (webpack-internal:///(rsc)/./node_modules/graphql/type/definition.js:139:39)
    at isRequiredArgument (webpack-internal:///(rsc)/./node_modules/graphql/type/definition.js:563:12)
    at Array.filter (<anonymous>)
    at ProvidedRequiredArgumentsOnDirectivesRule (webpack-internal:///(rsc)/./node_modules/graphql/validation/rules/ProvidedRequiredArgumentsRule.js:52:78)
    at eval (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/validation/validate-sdl.js:32:40)
    at Array.map (<anonymous>)
    at validateSDL (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/validation/validate-sdl.js:32:28)
    at runValidationRulesOnFilteredDocument (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/validation/validate-document.js:180:51)
    at validateDocument (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/validation/validate-document.js:224:5)
    at eval (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:287:51)
    at new Promise (<anonymous>)
    at Neo4jGraphQL.generateExecutableSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:283:16)
    at Neo4jGraphQL.getExecutableSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:103:42)
    at Neo4jGraphQL.getSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:99:21)
    at eval (webpack-internal:///(rsc)/./src/graphql/graphql.ts:28:32)
    at __webpack_require__.a (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./src/graphql/graphql.ts:1:21)
    at (rsc)/./src/graphql/graphql.ts (/Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:272:1)
    at __webpack_require__ (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/api/graphql/route.ts:7:74)
    at __webpack_require__.a (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./src/app/api/graphql/route.ts:1:21)
    at (rsc)/./src/app/api/graphql/route.ts (/Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:262:1)
    at __webpack_require__ (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fgraphql%2Froute&page=%2Fapi%2Fgraphql%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fgraphql%2Froute.ts&appDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:18:139)
    at __webpack_require__.a (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fgraphql%2Froute&page=%2Fapi%2Fgraphql%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fgraphql%2Froute.ts&appDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:1:21)
    at (rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fgraphql%2Froute&page=%2Fapi%2Fgraphql%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fgraphql%2Froute.ts&appDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2F[user]%2FDocuments%2Fcode%2Fgraphql-test&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (/Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:252:1)
    at __webpack_require__ (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:282:39)
    at /Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:283:1145
    at __webpack_require__.X (/Users/[user]/Documents/code/graphql-test/.next/server/webpack-runtime.js:197:21)
    at /Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:283:47
    at Object.<anonymous> (/Users/[user]/Documents/code/graphql-test/.next/server/app/api/graphql/route.js:286:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/Users/[user]/Documents/code/graphql-test/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:176:18)
    at requirePage (/Users/[user]/Documents/code/graphql-test/node_modules/next/dist/server/require.js:109:84)
    at /Users/[user]/Documents/code/graphql-test/node_modules/next/dist/server/load-components.js:59:84
    at async loadComponentsImpl (/Users/[user]/Documents/code/graphql-test/node_modules/next/dist/server/load-components.js:59:26)
    at async DevServer.findPageComponentsImpl (/Users/[user]/Documents/code/graphql-test/node_modules/next/dist/server/next-server.js:669:36) {
  page: '/api/graphql'
```

**Type definitions**
```graphql
type Movie {
  title: String
  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor {
  name: String
  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

**To Reproduce**
1. `npx create-next-app@latest`
2. Change target to es2017 and module to esnext in tsconfig.json
3. `npm install @neo4j/graphql graphql neo4j-driver @apollo/server @as-integrations/next graphql-tag`
4. Create local dbms using Neo4J Desktop
5. Load Movie data into local dbms
6. Create route.ts and graphql.ts (see below)
7. Access /api/graphql

/src/app/api/graphql/route.ts:
```ts
import { NextRequest } from 'next/server';
import handler from '@/graphql/graphql';
import 'server-only';

export async function GET(request: NextRequest) {
  return handler(request);
}

export async function POST(request: NextRequest) {
  return handler(request);
}
```

/src/graphql/graphql.ts:
```ts
import { NextRequest, NextResponse } from 'next/server';
import { Neo4jGraphQL } from '@neo4j/graphql';
import neo4j from 'neo4j-driver';

const typeDefs = `#graphql
  type Movie {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
  }

  type Actor {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
  }
`;

const driver = neo4j.driver(
  'bolt://localhost:7687',
  neo4j.auth.basic('neo4j', 'password')
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const schema = await neoSchema.getSchema();

const handler = (req: NextRequest) => {
  console.log(JSON.stringify(req));
  return new NextResponse(JSON.stringify(req));
};
export default handler;
```

**Expected behavior**
The endpoint should return a JSON version of the request sent

**System (please complete the following information):**

* OS: MacOS 14.1
* Version: @neo4j/graphql@16.8.1
* Node.js version: 21.1.0

**Additional context**
I have checked `npm ls graphql` and only one version is shown. The error appears on the call to `neoSchema.getSchema()`.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @forsakendaemon. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by forsakendaemon** [comment]
I'm sure there is something that I need to change about the way that modules are generated or something, but I have absolutely no idea what it is, so if this is not a bug but an error in configuration on my part, my apologies!

**Comment by forsakendaemon** [comment]
As an update: This same error happens with `graphql-yoga` as well. Again, there's only one version of `graphql` in `npm ls graphql`, and the error happens at the same place. I've tried adding an override (`"graphql": "$graphql"`), but the error persists.

**Comment by mjfwebb** [comment]
Hi @forsakendaemon can you please post your package.json?

**Comment by forsakendaemon** [comment]
```json
{
  "name": "graphql-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@apollo/server": "^4.9.5",
    "@neo4j/graphql": "^4.4.1",
    "graphql": "^16.8.1",
    "graphql-tag": "^2.12.6",
    "neo4j-driver": "^5.14.0",
    "next": "14.0.2",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.0.2",
    "typescript": "^5"
  }
}
```

**Comment by mjfwebb** [comment]
Hi @forsakendaemon, I took a look at this and was able to reproduce the problem you're encountering. Unfortunately, I haven't got any remedy for you at the moment, but rest assured that solving this is something we are interested in.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @forsakendaemon! :pray: We will now prioritise the bug and address it appropriately.

**Comment by sveinnfannar** [comment]
I’m also seeing this after updating from Next 13 to Next 14. It seems to be related to the RSC bundler (see `(rsc)/` in your stack trace paths) causing some dependencies to be included twice. The `graphql` library [uses `instanceof`](https://github.com/graphql/graphql-js/blob/0b7590f0a2b65e6210da2e49be0d8e6c27781af2/src/jsutils/instanceOf.ts#L17) which causes this to happen.

I’m not aware of this happening for others using graphql and Next 14 together so I wouldn’t rule out that this is caused by neo4j-graphql doing something fishy.

**Comment by darrellwarde** [comment]
> I’m also seeing this after updating from Next 13 to Next 14. It seems to be related to the RSC bundler (see `(rsc)/` in your stack trace paths) causing some dependencies to be included twice. The `graphql` library [uses `instanceof`](https://github.com/graphql/graphql-js/blob/0b7590f0a2b65e6210da2e49be0d8e6c27781af2/src/jsutils/instanceOf.ts#L17) which causes this to happen when an object is created with one copy of graphql and used with the other.
> 
> I’m not aware of this happening for others using graphql and Next 14 together so I wouldn’t rule out that this is caused by neo4j-graphql (or any of its dependencies) doing something fishy.
> 
> In any case, more people are going to update to Next 14 in the coming weeks and months so it would be great if someone from @neo4j-team-graphql could look into this (even though you seem to be caught in the middle)

This is a really helpful insight, thank you @sveinnfannar! We plan to spend some time looking at this next week, however, at this stage, we really don't know the extent and complexity of the issue!

**Comment by csmcallister** [comment]
I, too, am experiencing this exact issue in a new project I'm trying to start with next.js 14. I've been going mad since `npm ls graphql` shows a single, consistent version throughout my dependency tree.

**Comment by mjfwebb** [comment]
@forsakendaemon @sveinnfannar @csmcallister 

Hello again! Some good news, I've been able to circumvent the error using [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages) in `next.config.js` as follows:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ["graphql"],
  },
};

module.exports = nextConfig;
```

Please can you try this out too and let me know how it goes?

In the meantime, I will raise this with the NextJS team and see if anything more needs to be done on the graphql library side of things.

At the very least it seems it should be added to https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/server-external-packages.json

**Comment by sveinnfannar** [comment]
It works! Thanks for figuring this out @mjfwebb 😄

**Comment by forsakendaemon** [comment]
Yup, that works for me too, @mjfwebb. Thank you!
