### ISSUE TITLE
Aggregations with no result returns null but the GraphQL type is NonNull

### ISSUE THREAD

**Issue by mjfwebb** [neo4j/graphql#4615]
**Describe the bug**

When an aggregation is performed and there are no results, there is an error thrown from the library because the return value from the database is `null` but the GraphQL types are expecting `NonNull`.

Type definitions:
```graphql
interface Show {
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Movie implements Show {
    title: String!
    runtime: Int
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Series implements Show {
    title: String!
    episodes: Int
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Actor {
    name: String!
    actedIn: [Show!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

interface ActedIn @relationshipProperties {
    screenTime: Int
}
```

Example dataset
```cypher
// Create Movies
CREATE (m1:Movie { title: "The Movie One", cost: 10000000, runtime: 120 })
CREATE (m2:Movie { title: "The Movie Two", cost: 20000000, runtime: 90 })
CREATE (m3:Movie { title: "The Movie Three", cost: 12000000, runtime: 70 })

// Create Series
CREATE (s1:Series { title: "The Series One", cost: 10000000, episodes: 10 })
CREATE (s2:Series { title: "The Series Two", cost: 20000000, episodes: 20 })
CREATE (s3:Series { title: "The Series Three", cost: 20000000, episodes: 15 })

// Create Actors
CREATE (a1:Actor { name: "Actor One" })
CREATE (a2:Actor { name: "Actor Two" })

// Associate Actor 1 with Movies and Series
CREATE (a1)-[:ACTED_IN { screenTime: 100 }]->(m1)
CREATE (a1)-[:ACTED_IN { screenTime: 82 }]->(s1)
CREATE (a1)-[:ACTED_IN { screenTime: 20 }]->(m3)
CREATE (a1)-[:ACTED_IN { screenTime: 22 }]->(s3)

// Associate Actor 2 with Movies and Series
CREATE (a2)-[:ACTED_IN { screenTime: 240 }]->(m2)
CREATE (a2)-[:ACTED_IN { screenTime: 728 }]->(s2)
CREATE (a2)-[:ACTED_IN { screenTime: 728 }]->(m3)
CREATE (a2)-[:ACTED_IN { screenTime: 88 }]->(s3)
```

Query which produces the error with the given dataset:
Note: the title filter specified in the query deliberately has no matches.
```graphql
query {
  showsAggregate(where: {
    title_STARTS_WITH: "asdasdasd"
  }) {
    title {
      longest
    }
  }
}
```

Error returned:
```json
{
  "data": {},
  "errors": [
    {
      "message": "Cannot return null for non-nullable field StringAggregateSelectionNonNullable.longest.",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "showsAggregate",
        "title",
        "longest"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field StringAggregateSelectionNonNullable.longest.",
          "    at completeValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:605:13)",
          "    at executeField (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:646:12)",
          "    at completeValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:595:23)",
          "    at executeField (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/home/mike/dev/graphql/node_modules/graphql/execution/execute.js:646:12)"
        ]
      }
    }
  ]
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mjfwebb. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mjfwebb! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
Fixed in https://github.com/neo4j/graphql/pull/4623
