### ISSUE TITLE
node argument to createConnectionWhereAndParams is undefined when querying on Unions

### ISSUE THREAD

**Issue by LapoElisacci** [neo4j/graphql#488]
**Describe the bug**
When trying to perform a top level query filtering by a `Union` type the library returns an error:

**Type definitions**

Here's the schema:

```graphql
type Journalist {
  id: ID! @id
  name: String
  gender: Gender
  lang: String
  keywords: [Keyword]! @relationship(type: "HAS_KEYWORD", direction: OUT)
}

union Keyword = Emoji | Hashtag | Text

type Emoji {
  id: ID! @id
  type: String!
}

type Hashtag {
  id: ID! @id
  type: String!
}

type Text {
  id: ID! @id
  type: String!
}
```

Here's the query:

```graphql
query Query($journalistsWhere: JournalistWhere) {
  journalists(where: $journalistsWhere) {
    name
    keywords {
      ... on Emoji {
        type
      }
    }
  }
}
```

Here are the variables:

```json
{
  "journalistsWhere": {
    "keywordsConnection": {
      "Emoji": {
        "node": {
          "type": "Smile"
        }
      }
    }
  }
}
```

**To Reproduce**

1. Run the Apollo Server following the [official @neof4j/graphql documentation](https://neo4j.com/developer/graphql/)
2. Execute the above defined query
4. See the following error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'name' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "journalists"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'name' of undefined",
            "    at Object.entries.reduce.whereStrs (/app/node_modules/@neo4j/graphql/dist/translate/where/create-connection-where-and-params.js:65:55)",
            "    at Array.reduce (<anonymous>)",
            "    at Object.createConnectionWhereAndParams [as default] (/app/node_modules/@neo4j/graphql/dist/translate/where/create-connection-where-and-params.js:27:48)",
            "    at reducer (/app/node_modules/@neo4j/graphql/dist/translate/create-where-and-params.js:242:81)",
            "    at Array.reduce (<anonymous>)",
            "    at Object.createWhereAndParams [as default] (/app/node_modules/@neo4j/graphql/dist/translate/create-where-and-params.js:430:60)",
            "    at Object.translateRead (/app/node_modules/@neo4j/graphql/dist/translate/translate-read.js:72:56)",
            "    at /app/node_modules/@neo4j/graphql/dist/schema/resolvers/read.js:36:50",
            "    at Generator.next (<anonymous>)",
            "    at /app/node_modules/@neo4j/graphql/dist/schema/resolvers/read.js:8:71"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Expected behavior**
The query to work and to return the records filtered by its relationship

**System (please complete the following information):**

-   OS: [e.g. macOS]
-   Version: [e.g. @neo4j/graphql@2.2.0]
-   Node.js version: [e.g. 16.2.0]

**Comment by oskarhane** [comment]
Thanks for the report in this @LapoElisacci. We have had an eye on this and will dig into it soon.

**Comment by danstarns** [comment]
@LapoElisacci This is now released to npm under `2.4.0` apologies it took soo long to get this out to you. Thank you for your feedback and patience.

**Comment by LapoElisacci** [comment]
Hey @danstarns no worries at all! Thanks a lot for sorting this out.

**Comment by AlessioRussoIntroito** [comment]
Hi @danstarns, thanks a lot for your work. I think this issue occurs as well if you implement Interfaces instead of Unions. In the same scenario:

```graphql
type Journalist {
  id: ID! @id
  name: String
  gender: Gender
  lang: String
  keywords: [Keyword]! @relationship(type: "HAS_KEYWORD", direction: OUT)
}

interface Keyword {
  id: ID! @id
  type: String!
}

type Emoji implements Keyword {
  id: ID! @id
  type: String!
}

type Hashtag implements Keyword {
  id: ID! @id
  type: String!
}

type Text implements Keyword {
  id: ID! @id
  type: String!
}
```

Query:
```graphql
query Journalists($where: JournalistWhere) {
  journalists(where: $where) {
    name
  }
}
```
With both the following $where parameter:
1) First case
```graphql
{
  "where": {
    "keywordsConnection": {
      "node": {
        "type": "Smile"
      }
    }
  }
}
```
2) Second Case
```graphql
{
  "where": {
    "keywordsConnection": {
      "node": {
        "_on": {
          "Emoji": {
            "type": "Smile"
          }
        }
      }
    }
  }
}
```

They produce the following errors:
```graphql
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'name')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "journalists"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'name')",
            "    at /app/node_modules/@neo4j/graphql/dist/translate/create-where-and-params.js:276:55",
            "    at Array.forEach (<anonymous>)",
            "    at reducer (/app/node_modules/@neo4j/graphql/dist/translate/create-where-and-params.js:273:41)",
            "    at Array.reduce (<anonymous>)",
            "    at Object.createWhereAndParams [as default] (/app/node_modules/@neo4j/graphql/dist/translate/create-where-and-params.js:513:60)",
            "    at Object.translateRead (/app/node_modules/@neo4j/graphql/dist/translate/translate-read.js:89:56)",
            "    at /app/node_modules/@neo4j/graphql/dist/schema/resolvers/read.js:36:50",
            "    at Generator.next (<anonymous>)",
            "    at /app/node_modules/@neo4j/graphql/dist/schema/resolvers/read.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
