### ISSUE TITLE
Error when filtering on union relationships

### ISSUE THREAD

**Issue by dmoree** [neo4j/graphql#493]
#### Describe the bug
When using a union with the `@relationship` directive if the return type is `[{Union}!]!` an error will be thrown as non-matched nodes are returned as null.

#### Type definitions
```graphql
type Director {
  id: ID! @id
  name: String!

  movies: [Movie!]! @relationship(type: "DIRECTED", direction: OUT)
}

type Actor {
  id: ID! @id
  name: String!

  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}

union Person = Director | Actor

type Movie {
  id: ID! @id
  title: String!

  directors: [Director!]! @relationship(type: "DIRECTED", direction: IN)
  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)

  people: [Person!]! @relationship(type: "HAS_PERSON", direction: OUT)
}
```

#### To Reproduce

1. Clone repository
```
git clone git@github.com:dmoree/neo4j-graphql-issue-filter-union-field.git
```
2. Seed and start server
```
cd neo4j-graphql-issue-filter-union-field && yarn install && yarn seed && yarn start
```
3. Run the query in GraphiQL at `http://localhost:4000/graphql` (or as defined in `.env`)
###### Query
```graphql
query FilterPeopleByActorName {
  movies {
    people(where: {Actor: { name: "Keanu Reeves"}}) {
      ...on Actor {
        name
      }
    }
  }
}
```

###### Response
```
{
  "error": {
    "errors": [
      {
        "message": "Cannot return null for non-nullable field Movie.people.",
        "locations": [
          {
            "line": 3,
            "column": 5
          }
        ],
        "path": [
          "movies",
          0,
          "people",
          0
        ]
      }
    ],
    "data": null
  }
}
```

#### Expected Behavior
Expect to be able to filter union relationships by type.

###### Entire graph
![Screen Shot 2021-09-17 at 10 05 58 AM](https://user-images.githubusercontent.com/10360334/133827059-8c957de6-5658-4cf4-98b9-1ee19f057070.png)
###### Cypher Query
![Screen Shot 2021-09-17 at 10 14 26 AM](https://user-images.githubusercontent.com/10360334/133828047-f931271a-95cb-49ad-88ef-194cf69e2136.png)
#### System (please complete the following information):

-   OS: macOS@11.5.2
-   Version: @neo4j/graphql@2.2.0
-   Node.js version: 14.16.0

##### Debugger output
```
   @neo4j/graphql:graphql Incoming GraphQL:
Query:
query FilterPeopleByActorName {
  movies {
    people(where: {Actor: {name: "Keanu Reeves"}}) {
      ... on Actor {
        name
      }
    }
  }
}
Variables:
{} +0ms
  @neo4j/graphql:auth Verifying JWT +0ms
  @neo4j/graphql:auth JsonWebTokenError: invalid signature
    at /Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/jsonwebtoken/verify.js:133:19
    at getSecret (/Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/jsonwebtoken/verify.js:94:10)
    at Object.getJWT (/Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/@neo4j/graphql/src/auth/get-jwt.ts:74:35)
    at /Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/@neo4j/graphql/src/classes/Neo4jGraphQL.ts:158:31
    at /Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/dist/schema/src/addSchemaLevelResolver.js:57:21
    at /Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/dist/schema/src/addSchemaLevelResolver.js:32:41
    at new ValueOrPromise (/Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/value-or-promise/src/ValueOrPromise.ts:33:15)
    at /Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/dist/schema/src/addSchemaLevelResolver.js:32:16
    at resolveField (/Users/dmoree/projects/neo4j/graphql/issues/filter-union-field/node_modules/graphql/execution/execute.js:464:18) +2ms
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:Movie)
RETURN this { people:  [(this)-[:HAS_PERSON]->(this_people) WHERE "Actor" IN labels(this_people) | head( [ this_people IN [this_people] WHERE "Actor" IN labels (this_people) AND this_people.name = $this_people_Actor_name | this_people { __resolveType: "Actor",  .name } ] ) ]  } as this
Params:
{
  "this_people_Actor_name": "Keanu Reeves"
} +0ms
  @neo4j/graphql:execute Execute successful, received 1 records +12ms
```

**Comment by rcbevans** [comment]
Looking through this issue, this looks like we were both working on the same thing? 😆

https://github.com/neo4j/graphql/pull/495

I'll take a look at your change and figure out if they do indeed address the same problem, or if they're fixing different issues.

**Comment by dmoree** [comment]
I wouldn't think that there would be any overlap. The issue here is whether null values are filtered out from the cypher query. It is resolving the nodes correctly.

Here is the required change: https://github.com/neo4j/graphql/pull/494/commits/e03e427d7f9d0b2d6368e62809ebbcf936faf945

As you can see it is simply an oversight.
