### ISSUE TITLE
`Neo4jError: Invalid input 'WHERE': expected` when using auth in specific scenarios

### ISSUE THREAD

**Issue by afreakk** [neo4j/graphql#5023]
**Describe the bug**
We have had many of these kinds of errors, but I made a minimal reproduction of one here.

**Type definitions**
```
type JWT @jwt {
    id: String
}
type User @authorization(filter: [{ where: { node: { userId: "$jwt.id" } } }]) {
    userId: String! @unique
    adminAccess: [Tenant!]!
        @relationship(type: "ADMIN_IN", direction: OUT, aggregate: false)
}

type Tenant
    @authorization(
        validate: [{ where: { node: { admins: { userId: "$jwt.id" } } } }]
    ) {
    id: ID! @id
    admins: [User!]!
        @relationship(type: "ADMIN_IN", direction: IN, aggregate: false)
    settings: Settings!
        @relationship(type: "HAS_SETTINGS", direction: OUT, aggregate: false)
}

type Settings
    @authorization(
        validate: [
            { where: { node: { tenant: { admins: { userId: "$jwt.id" } } } } }
        ]
    ) {
    tenant: Tenant!
        @relationship(type: "HAS_SETTINGS", direction: IN, aggregate: false)
    extendedOpeningHours: [OpeningDay!]!
        @relationship(
            type: "HAS_OPENING_HOURS"
            direction: OUT
            aggregate: false
        )
}

type OpeningDay
    @authorization(
        validate: [
            {
                where: {
                    node: {
                        settings: { tenant: { admins: { userId: "$jwt.id" } } }
                    }
                }
            }
        ]
    ) {
    settings: Settings!
        @relationship(
            type: "HAS_OPENING_HOURS"
            direction: IN
            aggregate: false
        )
    date: Date
    open: [OpeningHoursInterval!]!
        @relationship(
            type: "HAS_OPEN_INTERVALS"
            direction: OUT
            aggregate: false
        )
}

type OpeningHoursInterval
    @authorization(
        validate: [
            {
                where: {
                    node: {
                        openingDay: {
                            settings: {
                                tenant: { admins: { userId: "$jwt.id" } }
                            }
                        }
                    }
                }
            }
        ]
    ) {
    openingDay: OpeningDay
        @relationship(
            type: "HAS_OPEN_INTERVALS"
            direction: IN
            aggregate: false
        )
    name: String
}

extend schema @authentication @query(read: true, aggregate: false)
```

**To Reproduce**

1. `git clone https://github.com/afreakk/n4j-issue.git`
2. `cd n4j-issue/`
3. `git checkout some-issue`
4. `yarn`
5. `./test.sh watch-test`
6. see error

**Expected behavior**
No error

**System (please complete the following information):**

* OS: linux
* Version: @neo4j/graphql@5.3.2
* Node.js version: 20.11.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @afreakk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Confirmed I see the same error.

Looks like a missing `WITH *` after a `CALL {}` on line 37 of the cypher below.

Tree:

```cypher
UpdateOperation
|──── ReadOperation
|     |──── NodeSelection
|     |──── AuthorizationFilters
|           |──── AuthorizationRuleFilter
|                 |──── AuthRelationshipFilter [admins] <SOME>
|                       |──── ParamPropertyFilter [userId] <EQ>
|     |──── OperationField <settings>
|           |──── ReadOperation
|                 |──── RelationshipSelection
|                 |──── AuthorizationFilters
|                       |──── AuthorizationRuleFilter
|                             |──── AuthRelationshipFilter [tenant] <SOME>
|                                   |──── AuthRelationshipFilter [admins] <SOME>
|                                         |──── ParamPropertyFilter [userId] <EQ>
|                 |──── OperationField <extendedOpeningHours>
|                       |──── ReadOperation
|                             |──── RelationshipSelection
|                             |──── AuthorizationFilters
|                                   |──── AuthorizationRuleFilter
|                                         |──── AuthRelationshipFilter [settings] <SOME>
|                                               |──── AuthRelationshipFilter [tenant] <SOME>
|                                                     |──── AuthRelationshipFilter [admins] <SOME>
|                                                           |──── ParamPropertyFilter [userId] <EQ>
|                             |──── OperationField <open>
|                                   |──── ReadOperation
|                                         |──── RelationshipSelection
|                                         |──── AuthorizationFilters
|                                               |──── AuthorizationRuleFilter
|                                                     |──── AuthRelationshipFilter [openingDay] <SOME>
|                                                           |──── AuthRelationshipFilter [settings] <SOME>
|                                                                 |──── AuthRelationshipFilter [tenant] <SOME>
|                                                                       |──── AuthRelationshipFilter [admins] <SOME>
|                                                                             |──── ParamPropertyFilter [userId] <EQ>
|                                         |──── AttributeField <name>
```

Cypher:

```
MATCH (this:Tenant)
WITH *
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {
    MATCH (this)<-[:ADMIN_IN]-(this0:User)
    WHERE ($jwt.id IS NOT NULL AND this0.userId = $jwt.id)
}), "@neo4j/graphql/FORBIDDEN", [0])


WITH this
CALL {
     WITH this
     MATCH (this)-[this_has_settings0_relationship:HAS_SETTINGS]->(this_settings0:Settings)
     OPTIONAL MATCH (this_settings0)<-[:HAS_SETTINGS]-(authorization__before_this0:Tenant)
     WITH *, count(authorization__before_this0) AS tenantCount
     WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (tenantCount <> 0 AND EXISTS {
         MATCH (authorization__before_this0)<-[:ADMIN_IN]-(authorization__before_this1:User)
         WHERE ($jwt.id IS NOT NULL AND authorization__before_this1.userId = $jwt.id)
     })), "@neo4j/graphql/FORBIDDEN", [0])


     WITH *
     CALL {
     WITH *
     OPTIONAL MATCH (this_settings0)-[this_settings0_extendedOpeningHours0_delete0_relationship:HAS_OPENING_HOURS]->(this_settings0_extendedOpeningHours0_delete0:OpeningDay)
     CALL {
         WITH this_settings0_extendedOpeningHours0_delete0
         MATCH (this_settings0_extendedOpeningHours0_delete0)<-[:HAS_OPENING_HOURS]-(authorization__before_this1:Settings)
         OPTIONAL MATCH (authorization__before_this1)<-[:HAS_SETTINGS]-(authorization__before_this2:Tenant)
         WITH *, count(authorization__before_this2) AS tenantCount
         WITH *
         WHERE (tenantCount <> 0 AND EXISTS {
             MATCH (authorization__before_this2)<-[:ADMIN_IN]-(authorization__before_this3:User)
             WHERE ($jwt.id IS NOT NULL AND authorization__before_this3.userId = $jwt.id)
         })
         RETURN count(authorization__before_this1) = 1 AS authorization__before_var0
     }
     WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND authorization__before_var0 = true), "@neo4j/graphql/FORBIDDEN", [0])
     WITH this_settings0_extendedOpeningHours0_delete0_relationship, collect(DISTINCT this_settings0_extendedOpeningHours0_delete0) AS this_settings0_extendedOpeningHours0_delete0_to_delete
     CALL {
             WITH this_settings0_extendedOpeningHours0_delete0_to_delete
             UNWIND this_settings0_extendedOpeningHours0_delete0_to_delete AS x
             DETACH DELETE x
     }
     }
     WITH this, this_settings0
     OPTIONAL MATCH (this_settings0)<-[:HAS_SETTINGS]-(authorization__after_this0:Tenant)
     WITH *, count(authorization__after_this0) AS tenantCount
     WITH *
     WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (tenantCount <> 0 AND EXISTS {
         MATCH (authorization__after_this0)<-[:ADMIN_IN]-(authorization__after_this1:User)
         WHERE ($jwt.id IS NOT NULL AND authorization__after_this1.userId = $jwt.id)
     })), "@neo4j/graphql/FORBIDDEN", [0])
     WITH this, this_settings0
     CALL {
             WITH this_settings0
             MATCH (this_settings0)<-[this_settings0_tenant_Tenant_unique:HAS_SETTINGS]-(:Tenant)
             WITH count(this_settings0_tenant_Tenant_unique) as c
             WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDSettings.tenant required exactly once', [0])
             RETURN c AS this_settings0_tenant_Tenant_unique_ignored
     }
     RETURN count(*) AS update_this_settings0
}
WITH this
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {
    MATCH (this)<-[:ADMIN_IN]-(authorization__after_this0:User)
    WHERE ($jwt.id IS NOT NULL AND authorization__after_this0.userId = $jwt.id)
}), "@neo4j/graphql/FORBIDDEN", [0])
WITH *
CALL {
     WITH this
     MATCH (this)-[this_settings_Settings_unique:HAS_SETTINGS]->(:Settings)
     WITH count(this_settings_Settings_unique) as c
     WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDTenant.settings required exactly once', [0])
     RETURN c AS this_settings_Settings_unique_ignored
}
WITH *
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {
    MATCH (this)<-[:ADMIN_IN]-(update_this0:User)
    WHERE ($jwt.id IS NOT NULL AND update_this0.userId = $jwt.id)
}), "@neo4j/graphql/FORBIDDEN", [0])
CALL {
    WITH this
    MATCH (this)-[update_this1:HAS_SETTINGS]->(update_this2:Settings)
    OPTIONAL MATCH (update_this2)<-[:HAS_SETTINGS]-(update_this3:Tenant)
    WITH *, count(update_this3) AS tenantCount
    WITH *
    WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND (tenantCount <> 0 AND EXISTS {
        MATCH (update_this3)<-[:ADMIN_IN]-(update_this4:User)
        WHERE ($jwt.id IS NOT NULL AND update_this4.userId = $jwt.id)
    })), "@neo4j/graphql/FORBIDDEN", [0])
    CALL {
        WITH update_this2
        MATCH (update_this2)-[update_this5:HAS_OPENING_HOURS]->(update_this6:OpeningDay)
        CALL {
            WITH update_this6
            MATCH (update_this6)<-[:HAS_OPENING_HOURS]-(update_this7:Settings)
            OPTIONAL MATCH (update_this7)<-[:HAS_SETTINGS]-(update_this8:Tenant)
            WITH *, count(update_this8) AS tenantCount
            WITH *
            WHERE (tenantCount <> 0 AND EXISTS {
                MATCH (update_this8)<-[:ADMIN_IN]-(update_this9:User)
                WHERE ($jwt.id IS NOT NULL AND update_this9.userId = $jwt.id)
            })
            RETURN count(update_this7) = 1 AS update_var10
        }
        WITH *
        WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND update_var10 = true), "@neo4j/graphql/FORBIDDEN", [0])
        CALL {
            WITH update_this6
            MATCH (update_this6)-[update_this11:HAS_OPEN_INTERVALS]->(update_this12:OpeningHoursInterval)
            CALL {
                WITH update_this12
                MATCH (update_this12)<-[:HAS_OPEN_INTERVALS]-(update_this13:OpeningDay)
                CALL {
                    WITH update_this13
                    MATCH (update_this13)<-[:HAS_OPENING_HOURS]-(update_this14:Settings)
                    OPTIONAL MATCH (update_this14)<-[:HAS_SETTINGS]-(update_this15:Tenant)
                    WITH *, count(update_this15) AS tenantCount
                    WITH *
                    WHERE (tenantCount <> 0 AND EXISTS {
                        MATCH (update_this15)<-[:ADMIN_IN]-(update_this16:User)
                        WHERE ($jwt.id IS NOT NULL AND update_this16.userId = $jwt.id)
                    })
                    RETURN count(update_this14) = 1 AS update_var17
                }
                WITH *
                WHERE update_var17 = true
                RETURN count(update_this13) = 1 AS update_var18
            }
            WITH *
            WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND update_var18 = true), "@neo4j/graphql/FORBIDDEN", [0])
            WITH update_this12 { .name } AS update_this12
            RETURN collect(update_this12) AS update_var19
        }
        WITH update_this6 { open: update_var19 } AS update_this6
        RETURN collect(update_this6) AS update_var20
    }
    WITH update_this2 { extendedOpeningHours: update_var20 } AS update_this2
    RETURN head(collect(update_this2)) AS update_var21
}
RETURN collect(DISTINCT this { settings: update_var21 }) AS data
```

Error:
```
@neo4j/graphql:execution Neo4jError: Invalid input 'WHERE': expected
  "CALL"
  "CREATE"
  "DELETE"
  "DETACH"
  "FOREACH"
  "IN"
  "INSERT"
  "LOAD"
  "MATCH"
  "MERGE"
  "NODETACH"
  "OPTIONAL"
  "REMOVE"
  "RETURN"
  "SET"
  "UNION"
  "UNWIND"
  "USE"
  "WITH"
  "}" (line 37, column 2 (offset: 1688))
"       WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND authorization__before_var0 = true), "@neo4j/graphql/FORBIDDEN", [0])"
  ^

    at captureStacktrace (../graphql/node_modules/neo4j-driver-core/lib/result.js:620:17)
    at new Result (../graphql/node_modules/neo4j-driver-core/lib/result.js:112:23)
    at newCompletedResult (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:523:12)
    at Object.run (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:355:20)
    at TransactionPromise.Transaction.run (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:181:34)
    at ManagedTransaction.run (../graphql/node_modules/neo4j-driver-core/lib/transaction-managed.js:54:21)
    at Executor.transactionRun (../graphql/packages/graphql/src/classes/Executor.ts:299:28)
    at ../graphql/packages/graphql/src/classes/Executor.ts:276:33
    at TransactionExecutor._safeExecuteTransactionWork (../graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:211:26)
    at TransactionExecutor.<anonymous> (../graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:198:46) {
  constructor: [Function],
  code: 'Neo.ClientError.Statement.SyntaxError',
  retriable: false
}
```

mutation:
```graphql
mutation {
  updateTenants(
    update: {
      settings: {
        update: {
          node: { extendedOpeningHours: [{ delete: [{ where: null }] }] }
        }
      }
    }
  ) {
    tenants {
      settings {
        extendedOpeningHours {
          open {
            name
          }
        }
      }
    }
  }
}
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @afreakk! :pray: We will now prioritise the bug and address it appropriately.
