### ISSUE TITLE
GraphQL parsing issue with `[[String!]]!`

### ISSUE THREAD

**Issue by mathix420** [neo4j/graphql#5142]
**Describe the bug**
Failed to parse this valid graphql type `[[String!]]!`

**Type definitions**
```graphql
Query {
  test(fields: [[String!]]!): String!
}
```

**To Reproduce**

1. Run a server with the given typedef

**Expected behavior**
Server should start

**Screenshots**

```
11 |  * Produces a GraphQLError representing a syntax error, containing useful
12 |  * descriptive information about the syntax error's position in the source.
13 |  */
14 | function syntaxError(source, position, description) {
15 |   return new _GraphQLError.GraphQLError(`Syntax Error: ${description}`, {
16 |     source,
        ^
GraphQLError: TypeError[Query.getPayFormFields]: TypeError[Query.getPayFormFields.fields]: Syntax Error: Unexpected character: "<".
 path: "undefined"
      at syntaxError (/home/mathix/projects/peach_api/node_modules/graphql/error/syntaxError.js:16:4)
      at readNextToken (/home/mathix/projects/peach_api/node_modules/graphql/language/lexer.js:430:9)
      at lookahead (/home/mathix/projects/peach_api/node_modules/graphql/language/lexer.js:392:16)
      at advance (/home/mathix/projects/peach_api/node_modules/graphql/language/lexer.js:336:12)
      at advanceLexer (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:1538:13)
      at expectToken (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:1393:13)
      at parseName (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:255:3)
      at parseNamedType (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:1455:3)
      at parseTypeReference (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:1416:12)
      at parseTypeReference (/home/mathix/projects/peach_api/node_modules/graphql/language/parser.js:1394:14)
```

**System (please complete the following information):**

* OS: [e.g. macOS, Windows] linux
* Version: [e.g. @neo4j/graphql@1.0.0] "@neo4j/graphql": "5.3.6",
* Node.js version: [e.g. 14.16.0] v18.18.2

**Additional context**

Ran using `bun run myserver.ts`.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.
