### ISSUE TITLE
Error: Unknown type "InventoryHolderInventoryConnectionSort" and "InventoryHolderInventoryConnection" for complex interface interactions

### ISSUE THREAD

**Issue by kozak-codes** [neo4j/graphql#558]
**Describe the bug**
I am having a hard time understanding _what_ is going on here on the latest master branch with this complex type def which has types which implement multiple interfaces. It seems as though if you implement multiple interfaces where an interface has a relationship in it or is composed of _just_ autogenerated/readonly types. I really don't know.

When create the Neo4jGraphql instance I get:

```
Error: Unknown type "InventoryHolderInventoryConnectionSort". Did you mean "InventoryHolderInventoryConnectionWhere", "InventoryHolderInventoryConnectFieldInput", "InventoryHolderInventoryUpdateConnectionInput", "InventoryHolderInventoryAggregateInput", or "InventoryHolderInventoryDisconnectFieldInput"?

Unknown type "InventoryHolderInventoryConnection". Did you mean "InventoryHolderInventoryConnectionWhere", "InventoryHolderInventoryConnectFieldInput", "InventoryHolderConnection", "InventoryHolderInventoryAggregateInput", or "InventoryHolderInventoryDisconnectFieldInput"?
    at assertValidSDL (/home/KleptoKat/projects/graphql/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/home/KleptoKat/projects/graphql/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at buildSchemaFromTypeDefinitions (/home/KleptoKat/projects/graphql/packages/graphql/node_modules/@graphql-tools/schema/index.cjs.js:211:26)
    at Object.makeExecutableSchema (/home/KleptoKat/projects/graphql/packages/graphql/node_modules/@graphql-tools/schema/index.cjs.js:803:32)
    at Object.makeAugmentedSchema (/home/KleptoKat/projects/graphql/packages/graphql/dist/schema/make-augmented-schema.js:903:29)
    at new Neo4jGraphQL (/home/KleptoKat/projects/graphql/packages/graphql/dist/classes/Neo4jGraphQL.js:60:59)
    at new OGM (/home/KleptoKat/projects/graphql/packages/ogm/dist/classes/OGM.js:41:27)
    at generateOGM (/home/KleptoKat/projects/merchantry/server/dist/neo4j.js:22:19)
    at /home/KleptoKat/projects/merchantry/server/dist/server.js:34:39
    at Generator.next (<anonymous>)
Instance exited with code 1
```

**Type definitions**

```graphql
interface Identifiable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
}

interface Ownable implements Identifiable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    owner: User @relationship(type: "OWNS", direction: IN)
}

type User implements Identifiable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    name: String
    owns: [Ownable!]!  @relationship(type: "OWNS", direction: OUT)
}

type Tile implements Ownable & Identifiable & InventoryHolder {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    owner: User @relationship(type: "OWNS", direction: IN)
    name: String
    inventory: Inventory! @relationship(type: "HAS_INVENTORY", direction: OUT)

}

type Inventory implements Identifiable & Ownable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    owner: User @relationship(type: "OWNS", direction: IN)
    holder: InventoryHolder  @relationship(type: "HAS_INVENTORY", direction: IN)

    maxWeight: Int!
    maxVolume: Int!
}

interface InventoryHolder {
    inventory: Inventory! @relationship(type: "HAS_INVENTORY", direction: OUT)
}
```

**To Reproduce**

1. Run a server with the schema abovve to see error

**Expected behavior**
Application should run.

**Screenshots**

**System (please complete the following information):**

-   OS: Linux
-   Version: branch: fix/556 (just off of master) https://github.com/neo4j/graphql/issues/556
-   Node.js version: 14

**Comment by KleptoKat** [comment]
I seem to have found the solution to my problem: do not duplicate decorators (eg @relationship, @id, etc) within the interface. Remove them entirely. That should clear up most errors.

**Comment by angrykoala** [comment]
Here is a slightly simpler typedefs that reproduce the problem:

```graphql
interface Identifiable {
    id: ID! @id
}

interface Ownable implements Identifiable {
    id: ID! @id
    owner: User @relationship(type: "OWNS", direction: IN)
}

type User implements Identifiable {
    id: ID! @id
    owns: [Ownable!]!  @relationship(type: "OWNS", direction: OUT)
}
```

With the following error:

```
Error: Unknown type "OwnableOwnerConnectionSort". Did you mean "OwnableOwnerConnectionWhere", "OwnableOwnerConnectFieldInput", "OwnableConnectInput", "OwnableDisconnectInput", or "OwnableOwnerUpdateConnectionInput"?

Unknown type "OwnableOwnerConnection". Did you mean "OwnableOwnerConnectionWhere", "OwnableOwnerConnectFieldInput", "OwnableConnectInput", "OwnableDisconnectInput", or "UserOwnsConnection"?
    at assertValidSDL (/home/angrykoala/Git/graphql/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/home/angrykoala/Git/graphql/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at Object.makeExecutableSchema (/home/angrykoala/Git/graphql/node_modules/@graphql-tools/schema/index.js:497:26)
    at new Neo4jGraphQL (/home/angrykoala/Git/graphql/packages/graphql/src/classes/Neo4jGraphQL.ts:87:24)
    at Object.<anonymous> (/home/angrykoala/Git/graphql/packages/graphql/test-api.ts:157:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

As mentioned, the problem seems related to duplicate decorators

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @KleptoKat! :pray: We will now prioritise the bug and address it appropriately.

**Comment by tbwiss** [comment]
Hi @KleptoKat!
At the moment we only have sparse and incomplete support for complex interface interactions. Or as in your case here interfaces implementing multiple interfaces. This most likely causes the error you experienced.
Addressing and supporting this fully will be a bigger undertaking and must therefore be thought through before we start working on it. It’s good to see that you found a workaround for the time being.

**Comment by darrellwarde** [comment]
In the upcoming 5.0.0 release, this works with the type definitions updated to be:

```gql
interface Identifiable {
    id: ID!
    createdAt: DateTime!
    updatedAt: DateTime!
}

interface Ownable implements Identifiable {
    id: ID!
    createdAt: DateTime!
    updatedAt: DateTime!
    owner: User @declareRelationship
}

type User implements Identifiable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    name: String
    owns: [Ownable!]! @relationship(type: "OWNS", direction: OUT)
}

type Tile implements Ownable & Identifiable & InventoryHolder {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    owner: User @relationship(type: "OWNS", direction: IN)
    name: String
    inventory: Inventory! @relationship(type: "HAS_INVENTORY", direction: OUT)
}

type Inventory implements Identifiable & Ownable {
    id: ID! @id
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    owner: User @relationship(type: "OWNS", direction: IN)
    holder: InventoryHolder @relationship(type: "HAS_INVENTORY", direction: IN)

    maxWeight: Int!
    maxVolume: Int!
}

interface InventoryHolder {
    inventory: Inventory! @declareRelationship
}
```
