### ISSUE TITLE
Missing the auth parameter in relationship projection subqueries

### ISSUE THREAD

**Issue by BertrandFritsch** [neo4j/graphql#601]
**Describe the bug**

With following GraphQL query with an auth role on every type:
```graphql
query Document {
  stakeholders {
    documents {
      customerContactConnection {
        edges {
          fileId
          uploadedAt
        }
      }
    }
  }
}
```

The library generates the following Cypher query:
```cypher
MATCH (this:Stakeholder)
CALL apoc.util.validate(NOT(ANY(r IN ["view"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0])
RETURN this { documents: [ (this)-[:REQUIRES]->(this_documents:Document)  WHERE apoc.util.validatePredicate(NOT(ANY(r IN ["view"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0]) | this_documents { customerContactConnection: apoc.cypher.runFirstColumn("CALL {
WITH this_documents
MATCH (this_documents)<-[this_documents_uploaded_relationship:UPLOADED]-(this_documents_customercontact:CustomerContact)
CALL apoc.util.validate(NOT(ANY(r IN [\"view\"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), \"@neo4j/graphql/FORBIDDEN\", [0])
WITH collect({ fileId: this_documents_uploaded_relationship.fileId, uploadedAt: apoc.date.convertFormat(toString(this_documents_uploaded_relationship.uploadedAt), \"iso_zoned_date_time\", \"iso_offset_date_time\") }) AS edges
RETURN { edges: edges, totalCount: size(edges) } AS customerContactConnection
} RETURN customerContactConnection", { this_documents: this_documents }, false) } ] } as this
```

Where one can observe that the query use a subquery for the `apoc.cypher.runFirstColumn` call with an auth check, but without the auth parameter.

The result:
```json
{
  "errors": [
    {
      "message": "Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.exceptions.ParameterNotFoundException: Expected parameter(s): auth",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "stakeholders"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Procedure.ProcedureCallFailed",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.exceptions.ParameterNotFoundException: Expected parameter(s): auth",
            "",
            "    at captureStacktrace (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\result.js:239:17)",
            "    at new Result (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\result.js:59:23)",
            "    at newCompletedResult (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\transaction.js:375:12)",
            "    at Object.run (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\transaction.js:229:20)",
            "    at Transaction.run (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\transaction.js:101:34)",
            "    at C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\@neo4j+graphql@2.4.0_4751c90ed1bf2b5f1fc2484aa9f1a4b9\\node_modules\\@neo4j\\graphql\\src\\utils\\execute.ts:98:35",
            "    at TransactionExecutor._safeExecuteTransactionWork (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:92:26)",
            "    at TransactionExecutor._executeTransactionInsidePromise (C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:83:34)",
            "    at C:\\Users\\bertr\\work\\projects\\portal-api\\node_modules\\.pnpm\\neo4j-driver-core@4.4.0\\node_modules\\neo4j-driver-core\\lib\\internal\\transaction-executor.js:40:19",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Type definitions**

```graphql
interface UploadedDocument @relationshipProperties {
  fileId: ID!
  uploadedAt: DateTime!
}

type Document @exclude(operations: [CREATE, UPDATE, DELETE]) {
  id: ID! @id
  stakeholder: Stakeholder! @relationship(type: "REQUIRES", direction: OUT)

  customerContact: CustomerContact @relationship(type: "UPLOADED", properties: "UploadedDocument", direction: IN)
}

extend type Document @auth(
  rules: [ { roles: [ "view" ] } ]
)

type CustomerContact @exclude(operations: [CREATE, UPDATE, DELETE]) {
  email: String!
  firstname: String!
  lastname: String!
  documents: [Document!]! @relationship(type: "UPLOADED", properties: "UploadedDocument", direction: OUT)
}

extend type CustomerContact @auth(
  rules: [ { roles: [ "view" ] } ]
)

type Stakeholder @exclude(operations: [CREATE, UPDATE, DELETE]) {
  id: ID!
  fields: String!
  documents: [Document!]! @relationship(type: "REQUIRES", direction: OUT)
}

extend type Stakeholder @auth(
  rules: [ { roles: [ "view" ] } ]
)
```
**Expected behavior**

The auth parameter should be propagated to the subquery.

**System (please complete the following information):**

-   OS: Windows
-   Version: @neo4j/graphql@2.4.0
-   Node.js version: 17.0.1

**Additional context**

Actually, to reproduce this behaviour with version 2.4.0, the #600 bug has first to be fixed otherwise this error will not pop up.

**Comment by darrellwarde** [comment]
For sure, definitely an issue here. Logged internally, we'll try to get a look at this before we do our next release. 🙂
