### ISSUE TITLE
input.map is not a function (with connectOrCreate)

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#619]
Hi thanks for releasing 2.5.0, really exciting and trying to get going with it. I have a fairly complicated query, and when I run it it's currently giving me this error:

```json
 {
      "message": "input.map is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateWidgets"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: input.map is not a function",
            "    at Object.createConnectOrCreateAndParams 
....
```

And here's my query. 

It's a little complicated but here's what the deal is:

The node types are: `Fact`, `Topic`, `User`, and `Vote`.

They connect like this:

```
(t:Topic)-[:VOTE_HAS_THING]-(v:Vote)-[:VOTE_HAS_FACT]-(d:Detail)
(u:User)-[:VOTED]-(v:Vote)
```
So below I'm trying to say: take this Detail that I have, and if I have a Vote ID then find that and add a new user_votes. If I don't have one, onCreate then it should add the `type`, and connect `Topic`, `Fact`, and to `User`. I'm not positive it will add the user_votes relationship if there is a connect, I would have imagined there would have been an `onConnect` function but I don't see that one exists. Any idea what this error message is from?

```gql
mutation {
updateFacts(
  where: { id: "5d081f2e-7663-4ac1-9c18-f087c35b7042"},
  connectOrCreate: {
    votes: {
      where: { node: { id: "lmnop"}},
      onCreate: { 
        node: { 
          type: "detailVote",
          topic: { connect: { where: { node: { id: "21732715-2aa2-4c4b-9c45-ea4985f2113c" }}}},
          fact: { connect: { where: { node: { id: "5d081f2e-7663-4ac1-9c18-f087c35b7042" }}}},
          user_votes: { connect: {where: {node: { id: "YSCbEHFxm0gnXOPEKmRb8WUVO7j2"}}}}
        }
      }
    }
  }
)
  {
    facts	{
      id
      dataValue
      votes	{
        id
         user_votes{
          id
          name
        }
      }
    }
  }

  
}```

**Comment by mobsean** [comment]
I can confirm that bug. Also getting `input.map is not a function`

`"TypeError: input.map is not a function",
            "    at Object.createConnectOrCreateAndParams (.......\\node_modules\\@neo4j\\graphql\\src\\translate\\connect-or-create\\create-connect-or-create-and-params.ts:53:30)",`

**Comment by darrellwarde** [comment]
For anyone who's been able to reproduce this problem, could you please provide some type definitions and an offending Mutation so that we can try to reproduce ourselves and fix? Thanks!

**Comment by mobsean** [comment]
> For anyone who's been able to reproduce this problem, could you please provide some type definitions and an offending Mutation so that we can try to reproduce ourselves and fix? Thanks!

I think there is something wrong with one-to-many relationships, many-to-many does not raise the error.

typeDef:
```
type foo {
  id: ID @unique
  Name: String
  Age: Int
  DrinksAt: bar @relationship(type:"DRINKS_AT", direction: OUT)
}

type bar {
  id: ID @unique
  Adress: String
  Customers: [foo] @relationship(type:"DRINKS_AT", direction: IN)
}
```

then mutation creatingfoos with connectOrCreate:
```
mutation {
  createfoos(
    input: {
      DrinksAt: {
        connectOrCreate: {
          where: { node: { id: "b50bd49b-9295-4749-9c0e-91d1e16df0b5" } }
          onCreate: { node: { Adress: "Some Street" } }
        }
      }
    }
  ) {
    info {
      nodesCreated
    }
  }
}

```

will give you:
```
{
  "errors": [
    {
      "message": "input.map is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createfoos"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: input.map is not a function",
            "    at Object.createConnectOrCreateAndParams (...\\node_modules\\@neo4j\\graphql\\src\\translate\\connect-or-create\\create-connect-or-create-and-params.ts:53:30)",
            "    at ...\\node_modules\\@neo4j\\graphql\\src\\translate\\create-create-and-params.ts:149:75",
            "    at Array.forEach (<anonymous>)",
            "    at reducer (...\\node_modules\\@neo4j\\graphql\\src\\translate\\create-create-and-params.ts:82:22)",
            "    at Array.reduce (<anonymous>)",
            "    at Object.createCreateAndParams [as default] (...\\node_modules\\@neo4j\\graphql\\src\\translate\\create-create-and-params.ts:235:59)",
            "    at resolveTree.args.input.reduce.createStrs (...\\node_modules\\@neo4j\\graphql\\src\\translate\\translate-create.ts:48:58)",
            "    at Array.reduce (<anonymous>)",
            "    at Object.translateCreate (...\\node_modules\\@neo4j\\graphql\\src\\translate\\translate-create.ts:42:70)",
            "    at ...\\node_modules\\@neo4j\\graphql\\src\\schema\\resolvers\\create.ts:31:34"
          ]
        }
      }
    }
  ],
  "data": null
}
```


The other way around seems to work:
````
mutation {
  createbars(
    input: [
      {
      Adress: "Middle Earth"
      Customers: {
        connectOrCreate: {
          where: { node: { id: "b50bd49b-9295-4749-9c0e-91d1e16df0b5" } }
          onCreate: { node: { Name: "Gandalf" } }
        }
      }
      }
    ]
  ) {
    info {
      nodesCreated
    }
  }
}
```
