### ISSUE TITLE
"Variable `...Connection` not defined"

### ISSUE THREAD

**Issue by munyirik** [neo4j/graphql#630]
Using package version: 2.5.0.

I have a schema that looks something like this:
```graphql
    workers: [User!]!
      @cypher(
        statement: """
        MATCH p = (this)-[*]->(u)<-[:HAS_REVIEWED]-()
        RETURN DISTINCT u
        """
      )
    reviewers: [User!]! @relationship(type: "HAS_REVIEWED", properties: "Review", direction: IN)
```

If I run the following query, it's successful:
```graphql
query Users($where: UserWhere) {
  users(where: $where) {
    workers {
      id
    }
    reviewersConnection {
      totalCount
    }
  }
}
```

If I run the following query, it fails:
```graphql
query Users($where: UserWhere) {
  users(where: $where) {
    workers {
      id
      reviewersConnection {
        totalCount
      }
    }
  }
}
```

Error:
```
 "stacktrace": [
            "Neo4jError: Variable `reviewersConnection` not defined (line 4, column 83 (offset: 257))",
            "\"RETURN u\", {this: this, auth: $auth}, true) | this_workers { .id, .role, reviewersConnection }] } as this\"",
            "                                                                                   ^",
            "",
            "    at captureStacktrace (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/result.js:239:17)",
            "    at new Result (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/result.js:59:23)",
            "    at newCompletedResult (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/transaction.js:372:12)",
            "    at Object.run (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/transaction.js:226:20)",
            "    at Transaction.run (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/transaction.js:98:34)",
            "    at /Users/munyiri/source/service/node_modules/@neo4j/graphql/src/utils/execute.ts:105:35",
            "    at TransactionExecutor._safeExecuteTransactionWork (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)",
            "    at /Users/munyiri/source/service/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19",
            "    at new Promise (<anonymous>)"
          ]
```

Is there something I'm doing wrong? the expectation is that the autogenerated `reviewersConnection` should work in the nested object.

**Comment by danstarns** [comment]
Your expectation is valid and you haven't done anything wrong, this is a bug on our end when projecting connection fields after a `@cypher` projection. Tracked and we will look into this shortly. Thank you for the clear report!
