### ISSUE TITLE
connectOrCreate throws error when used with auth

### ISSUE THREAD

**Issue by fab679** [neo4j/graphql#923]
```gql
type User @exclude(operations: [READ]) {
  id: ID! @id
  name: String!
  email: String! @unique
  password: String! @private
  bio: String
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime @timestamp(operations: [UPDATE])
  blogs: [BlogPost] @relationship(type: "PUBLISHED", direction: OUT)
}

type BlogPost
  @fulltext(indexes: [{ name: "BlogTitle", fields: ["title", "content"] }]) {
  id: ID! @id
  title: String!
  featuredImage: String
  slug: String! @unique
  excerpt: String!
  content: String!
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime @timestamp(operations: [UPDATE])
  author: User! @relationship(type: "PUBLISHED", direction: IN)
  published: Boolean!
  featured: Boolean!
  categories: [Category!]! @relationship(type: "IN_CATEGORY", direction: OUT)
}

type Category {
  id: ID! @id
  name: String! @unique
  blogs: [BlogPost] @relationship(type: "IN_CATEGORY", direction: IN)
}

type Mutation {
  SignIn(email: String!, password: String!): String! ##jwt
  SignUp(name: String!, email: String!, password: String!): String! ##jwt
}

type Query {
  GetUser: User!
}

extend type BlogPost
  @auth(
    rules: [
      { operations: [UPDATE], allow: { author: { id: "$jwt.sub" } } }
      { operations: [UPDATE], bind: { author: "$jwt.sub" } }
      {
        operations: [CREATE, UPDATE, CONNECT, DISCONNECT, DELETE]
        isAuthenticated: true
      }
    ]
  )

extend type Category
  @auth(
    rules: [
      {
        operations: [CREATE, UPDATE, DELETE, DISCONNECT, CONNECT]
        isAuthenticated: true
      }
    ]
  )
```

I'm getting the Error below on trying to create a BlogPost with connectOrCreate
```  
@neo4j/graphql:execute Neo4jError: WITH is required between MERGE and CALL (line 32, column 1 (offset: 1269))
"CALL apoc.util.validate(NOT(apoc.util.validatePredicate(NOT($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])"
 ^

    at captureStacktrace (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\result.js:239:17)
    at new Result (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\result.js:59:23)
    at newCompletedResult (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\transaction.js:375:12)
    at Object.run (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\transaction.js:229:20)
    at Transaction.run (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\transaction.js:101:34)
    at C:\Users\MAIN PC\Desktop\school\backend\node_modules\@neo4j\graphql\dist\utils\execute.js:66:104
    at TransactionExecutor._safeExecuteTransactionWork (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:92:26)
    at TransactionExecutor._executeTransactionInsidePromise (C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:83:34)
    at C:\Users\MAIN PC\Desktop\school\backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:40:19
    at new Promise (<anonymous>) {
  constructor: [Function: Neo4jError],
  code: 'Neo.ClientError.Statement.SyntaxError'
} +932ms
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @fab679. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @fab679, 
Indeed this seems to be a bug with the library, to make sure that we properly fix it I see the exact `connectOrCreate` query and params that produce this problem?

**Comment by angrykoala** [comment]
For reference, the following simplified typedefs:
```graphql
    type BlogPost @fulltext(indexes: [{ name: "BlogTitle", fields: ["title"] }]) {
        title: String!
        slug: String! @unique
    }

    type Category {
        name: String! @unique
        blogs: [BlogPost!]! @relationship(type: "IN_CATEGORY", direction: IN)
    }

    extend type BlogPost
        @auth(
            rules: [
                { operations: [UPDATE], allow: { author: { id: "$jwt.sub" } } }
                { operations: [UPDATE], bind: { author: "$jwt.sub" } }
                { operations: [CREATE, UPDATE, CONNECT, DISCONNECT, DELETE], isAuthenticated: true }
            ]
        )

    extend type Category
        @auth(rules: [{ operations: [CREATE, UPDATE, DELETE, DISCONNECT, CONNECT], isAuthenticated: true }])
```

Along with the following query:
```graphql
mutation {
  createCategories(
    input: [{ blogs: { connectOrCreate: [{
      where: {
        node: {
          slug: "dsa"
        }
      },
      onCreate: {
        node: {
          title: "mytitle",
          slug: "myslug"
        }
      }
    }] }, name: "myname" }]
  ) {
    info {
      nodesCreated
    }
  }
}
```

Results in the error:
```
Neo4jError: WITH is required between SET and CALL (line 4, column 1 (offset: 60))
"CALL apoc.util.validate(NOT(apoc.util.validatePredicate(NOT($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])"
```

Wich seems to be caused by the same problem as the one described above

**Comment by fab679** [comment]
> We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @fab679! :pray: We will now prioritise the bug and address it appropriately.

Thanks for for taking your time to review it.
