### ISSUE TITLE
Can't query nodes that have a DateTime field

### ISSUE THREAD

**Issue by catherineluse** [neo4j/graphql#941]
**Describe the bug**

After following these introductory docs https://neo4j.com/docs/graphql-manual/current/getting-started/ , I tried adding a DateTime field to a type. While I have been able to successfully create a node with a DateTime, I get errors when trying to query the node with the DateTime field. The expected behavior is that I would get the same DateTime value that I put in. The bug is either a) the database should have thrown an error (if I created an invalid DateTime), or b) if my DateTime was valid, I should have been able to query it after creating it.

I started with a Movie type in that tutorial and then added a startTime field to it:

```
type Movie {
        title: String
        actors: [Actor] @relationship(type: "ACTED_IN", direction: IN)
        startTime: DateTime
    }
```

When creating a movie with a startTime, the movie was created successfully:

```
mutation {
  createMovies (input: {
      title: "Test"
      startTime: "2022-02-07T01:13:43.342Z"
  }){
    movies {
      title
    }
  }
}

```
However, querying the movie results in an error when the startTime field is included in the query:

```
query Query {
  movies {
    title
    startTime
  }
}

```
The full error is:

```
{
	"errors": [
		{
			"message": "Unknown function 'apoc.date.convertFormat' (line 2, column 34 (offset: 52))\n\"RETURN this{.title, startTime: apoc.date.convertFormat(toString(this.startTime), \"iso_zoned_date_time\", \"iso_offset_date_time\")} AS this\"\n                                  ^",
			"locations": [
				{
					"line": 2,
					"column": 2
				}
			],
			"path": [
				"movies"
			],
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"exception": {
					"code": "Neo.ClientError.Statement.SyntaxError",
					"name": "Neo4jError",
					"stacktrace": [
						"Neo4jError: Unknown function 'apoc.date.convertFormat' (line 2, column 34 (offset: 52))",
						"\"RETURN this{.title, startTime: apoc.date.convertFormat(toString(this.startTime), \"iso_zoned_date_time\", \"iso_offset_date_time\")} AS this\"",
						"                                  ^",
						"",
						"    at captureStacktrace (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/result.js:239:17)",
						"    at new Result (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/result.js:59:23)",
						"    at newCompletedResult (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/transaction.js:375:12)",
						"    at Object.run (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/transaction.js:229:20)",
						"    at Transaction.run (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/transaction.js:101:34)",
						"    at /Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/@neo4j/graphql/dist/utils/execute.js:66:104",
						"    at TransactionExecutor._safeExecuteTransactionWork (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)",
						"    at TransactionExecutor._executeTransactionInsidePromise (/Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34)",
						"    at /Users/catherineluse/gennit-vue/neo4j-graphql-example/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:40:19",
						"    at new Promise (<anonymous>)"
					]
				}
			}
		}
	],
	"data": null
}
```
My full code is:
https://github.com/catherineluse/neo4j-graphql-example/blob/main/index.js

**Type definitions**
```
type Movie {
        title: String
        actors: [Actor] @relationship(type: "ACTED_IN", direction: IN)
        startTime: DateTime
    }
```

**To Reproduce**

1. Run a server with the Movie type
2. Execute the mutation
```
mutation {
  createMovies (input: {
      title: "Test2"
      startTime: "2022-02-07T01:13:43.342Z"
  }){
    movies {
      title
    }
  }
}
```
3. Execute the query
```
query Query {
  movies {
    title
    startTime
  }
}
```

**Expected behavior**
Querying the Movie with the startTime should return the startTime in the same format that I created it in: an ISO string (originally created from a new Javascript Date())

**Screenshots**

**System (please complete the following information):**

* OS: [e.g. macOS, Windows] macOS
* Version: [e.g. @neo4j/graphql@1.0.0] 2.5.6
* Node.js version: [e.g. 14.16.0] 16.13.2

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @catherineluse. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by dmoree** [comment]
@catherineluse Is the APOC library installed for the database in question?

**Comment by catherineluse** [comment]
No, how do you install it?

If it's a prerequisite for getting started with the Neo4j GraphQL library, then this is a docs bug because it should be documented under dependencies: https://neo4j.com/docs/graphql-manual/current/getting-started/#_install_dependencies

**Comment by dmoree** [comment]
It is actually listed here:
https://neo4j.com/docs/graphql-manual/current/introduction/#_requirements

As it is a requirement of the database itself it is not listed in the dependency list.

If you are using Neo4j Desktop, select the database you are using and in the sidebar there will be a tab called "Plugins". The first one will be APOC. Expand that and click "Install".

**Comment by catherineluse** [comment]
OK, thank you. 

I've suggested two docs changes that would help a beginner like me in the future:

- https://github.com/neo4j/graphql/pull/943
- https://github.com/neo4j/graphql/pull/942

**Comment by angrykoala** [comment]
Hi, @catherineluse Thanks for the doc suggestions. I assume this issue can be closed then?

**Comment by catherineluse** [comment]
Yes, thank you
